"use client";

import { useLanguage } from "@/lib/i18n/LanguageProvider";

/**
 * Sales-dashboard strings added by the 6 Sep 2026 review fixes.
 *
 * Kept beside the pages rather than in lib/i18n because that dictionary
 * is being edited concurrently for the customer and technician apps;
 * the shape is checked the same way — `en` is typed from `th`, so a key
 * missing in either language fails `tsc`.
 */
const th = {
  errors: {
    suspended: "ร้านถูกระงับการใช้งาน ทำรายการใหม่ไม่ได้",
    forbidden: "คุณไม่มีสิทธิ์ทำรายการนี้",
    notFound: "ไม่พบรายการนี้แล้ว",
    conflict: "ทำรายการไม่ได้ในสถานะปัจจุบัน",
    invalid: "ข้อมูลไม่ถูกต้อง ตรวจช่องที่กรอกอีกครั้ง",
    failed: "ทำรายการไม่สำเร็จ ({status})",
    readOnly: "ดูได้อย่างเดียว — ต้องมีสิทธิ์ \"{permission}\" จึงจะแก้ไขได้",
    showingLatest: "แสดง {count} รายการล่าสุด",
  },
  reasons: {
    deal_has_no_products: "ดีลนี้ยังไม่มีสินค้า เพิ่มสินค้าในดีลก่อน",
    quote_transition_not_allowed: "เปลี่ยนสถานะใบเสนอราคาแบบนี้ไม่ได้",
    company_incomplete: "ยังออกเอกสารไม่ได้ ต้องกรอกข้อมูลบริษัทก่อน: {fields}",
    already_issued: "ใบนี้ออกเอกสารไปแล้ว ถ้าต้องการออกใหม่ให้ยืนยันอีกครั้ง",
    transfer_already_pending: "มีคำขอโอนความเป็นเจ้าของค้างอยู่แล้ว",
    transfer_target_is_self: "เลือกสมาชิกคนอื่นเป็นเจ้าของคนใหม่",
    not_owner: "เฉพาะเจ้าของร้านคนปัจจุบันเท่านั้นที่โอนได้",
    not_nominee: "คำขอโอนนี้ไม่ได้ส่งถึงคุณ",
    transfer_not_pending: "คำขอโอนนี้ถูกใช้ไปแล้ว",
    member_not_active: "สมาชิกคนนี้ไม่ได้อยู่ในร้านแล้ว",
    already_exists: "มีชื่อนี้อยู่แล้ว",
    duplicate: "มีรายการนี้อยู่แล้ว ({code})",
    dispatch_blocked: "ยังมอบหมายไม่ได้ ขาด: {fields}",
    tenant_suspended: "ร้านถูกระงับการใช้งาน ทำรายการใหม่ไม่ได้",
    reason_required: "ต้องระบุเหตุผล",
    staff_only: "เฉพาะพนักงานของร้าน",
    invoice_state: "ใบแจ้งหนี้อยู่ในสถานะที่ทำรายการนี้ไม่ได้ (ต้องออกเอกสารก่อนรับชำระ · ใบเสร็จออกได้เมื่อชำระครบ)",
    payment_invalid: "จำนวนเงินไม่ถูกต้อง — ต้องมากกว่า 0 และไม่เกินยอดค้าง",
  },
  customers: {
    lastNameAndPhone: "ต้องมีนามสกุลและเบอร์โทร (ชื่อจะเว้นก็ได้)",
  },
  deals: {
    finalStage: "ดีลนี้ปิดแล้ว — สถานะสุดท้าย",
    lostReasonTitle: "ปิดดีลไม่สำเร็จ — เพราะอะไร",
    lostReasonHint: "เว้นว่างได้ แต่เหตุผลช่วยให้รู้ว่าแพ้เพราะอะไรบ่อย",
    confirmLost: "บันทึกว่าปิดไม่สำเร็จ",
    needsQuoteCreate: "ต้องมีสิทธิ์สร้างใบเสนอราคา",
  },
  quotes: {
    markSent: "ส่งให้ลูกค้าแล้ว",
    markExpired: "หมดอายุแล้ว",
    issueBeforeSend: "ออกเอกสารก่อน แล้วค่อยบันทึกว่าส่งให้ลูกค้าแล้ว",
    final: "ใบเสนอราคานี้ปิดแล้ว เปลี่ยนสถานะไม่ได้อีก",
    needsUpdate: "ต้องมีสิทธิ์แก้ไขใบเสนอราคาจึงจะออกเอกสารหรือเปลี่ยนสถานะได้",
  },
  tickets: {
    latestOnly: "แสดงเฉพาะงานที่ยังไม่จบ (สูงสุด {count} รายการต่อสถานะ)",
  },
  warranties: {
    serialSearch: "ค้นหาตาม S/N",
    serialSearchHint: "พิมพ์หมายเลขเครื่องให้ครบแล้วกดค้นหา",
    search: "ค้นหา",
    clearSearch: "แสดงทั้งหมด",
    serialNotFound: "ไม่พบเครื่องหมายเลข {serial} ในร้านนี้",
  },
  products: {
    codeLocked: "รหัสสินค้าแก้ไม่ได้ — รหัสใหม่คือสินค้าใหม่ ให้เพิ่มสินค้าใหม่แทน",
    readOnly: "ดูรายการได้ ต้องมีสิทธิ์จัดการสินค้าจึงจะเพิ่มหรือแก้ไขได้",
    archive: "เก็บถาวร",
    archiveAction: "เก็บถาวรสินค้า",
    archiveMany: "เก็บถาวร ({n})",
    archiveManyTarget: "สินค้า {n} รายการ",
    archiveKeepsDeals: "ดีลและใบเสนอราคาที่มีสินค้านี้ยังอยู่ครบ ไม่ถูกแก้",
    archiveKeepsRow: "เก็บถาวร ไม่ได้ลบทิ้ง · หายจากรายการและจากตัวเลือกตอนเพิ่มสินค้าในดีล",
    archived: "เก็บถาวร {name} ({code}) แล้ว · ดีลเดิมยังอยู่",
  },
  transfer: {
    ownerTitle: "เจ้าของ",
    currentOwner: "ดูแลโดย",
    nobody: "ยังไม่มีผู้ดูแล",
    someoneElse: "สมาชิกที่ไม่อยู่ในรายชื่อแล้ว",
    handTo: "โอนให้",
    pickColleague: "เลือกพนักงาน…",
    hint: "เลือกชื่อแล้วระบบจะถามยืนยันก่อนโอน · ในแชท: \"โอนลูกค้า สมชาย ให้ สมหญิง\"",
    action: "โอนให้ {name}",
    affects: "{name} จะได้รับแจ้งใน LINE และเห็นรายการนี้เป็นของตัวเอง",
    reversible: "โอนกลับได้ทุกเมื่อด้วยช่องเดียวกัน",
    done: "โอน {label} ให้ {name} แล้ว",
    denied: "คุณไม่มีสิทธิ์โอนงานให้ผู้รับผิดชอบคนอื่น",
    many: "เปลี่ยนเจ้าของ ({n})",
    manyTitle: "เปลี่ยนเจ้าของ {n} รายการ",
    manyHint: "ทุกรายการที่เลือกจะไปอยู่กับคนเดียวกัน · คนที่ได้รับจะได้รับแจ้งใน LINE",
    manyConfirm: "โอน {n} รายการให้ {name}",
  },
  satisfaction: {
    title: "ความพึงพอใจ",
    intro: "คะแนนที่ลูกค้าให้หลังปิดงานซ่อม (1 = ไม่ดี · 3 = ดีเยี่ยม) — ระบบส่งแบบสำรวจให้ลูกค้าเองทุกครั้งที่งานปิด",
    period: "ช่วงเวลา",
    days30: "30 วัน",
    days90: "90 วัน",
    days365: "12 เดือน",
    average: "คะแนนเฉลี่ย",
    outOf: "จาก 3",
    answered: "ตอบแล้ว",
    pending: "รอตอบ",
    responseRate: "อัตราตอบ",
    responseHint: "ตอบแล้ว {answered} จากที่ส่งไป {sent} ใบ",
    distribution: "กระจายคะแนน",
    byTechnician: "แยกตามช่าง",
    technician: "ช่าง",
    answers: "คำตอบ",
    noTechnicians: "ยังไม่มีคำตอบที่ระบุช่างได้ (งานที่ยังไม่ได้มอบหมายให้ใคร)",
    recent: "คำตอบล่าสุด",
    noAnswers: "ยังไม่มีคำตอบในช่วงนี้",
    pendingNote: "{n} ใบยังรอลูกค้าตอบ",
    comment: "ความเห็น",
    noPermission: "บัญชีของคุณยังไม่มีสิทธิ์ดูรายงาน ขอให้เจ้าของร้านเปิดสิทธิ์ \"ดูรายงาน\" ให้",
    chatHint: "ในแชท: \"คะแนนความพึงพอใจ\" หรือ \"ความพึงพอใจของช่าง สมศักดิ์\"",
  },
  rules: {
    title: "กฎมอบหมายงานอัตโนมัติ",
    intro: "งานซ่อมใหม่และลูกค้าใหม่ถูกแจกให้ทีมตามกฎนี้ · ตั้งในแชทด้วย \"ตั้งกฎมอบหมาย …\" หรือพิมพ์นโยบายด้านล่าง",
    none: "ยังไม่มีกฎ — งานใหม่ต้องมอบหมายเอง",
    scopeTechnician: "กฎช่าง (งานซ่อม)",
    scopeSales: "กฎฝ่ายขาย (ลูกค้าใหม่)",
    scope: "ขอบเขต",
    conditions: "เงื่อนไข",
    noConditions: "ไม่มีเงื่อนไข — ใช้กับทุกงาน",
    conditionLine: "ถ้า {field} {operator} {value} → ทีม {team}",
    strategy: "วิธีเลือกคน",
    strategies: { least_load: "คนที่งานน้อยที่สุด", round_robin: "สลับกันไปตามลำดับ", first_available: "คนแรกที่ว่าง" },
    capacity: "จำกัดงานต่อวัน",
    noCapacity: "ไม่จำกัด",
    capacityLine: "วันละ {n} งาน ({mode})",
    hardBlock: "ห้ามเกิน",
    softWarn: "เกินได้แต่จะเตือน",
    fields: { "product.category": "หมวดสินค้า", "product.name": "ชื่อสินค้า", "customer.stage": "สถานะลูกค้า", "customer.source": "ที่มาลูกค้า" },
    operators: { equals: "คือ", not_equals: "ไม่ใช่", in: "อยู่ใน", contains: "มีคำว่า", gt: "มากกว่า", gte: "ตั้งแต่", lt: "น้อยกว่า", lte: "ไม่เกิน" },
    edit: "แก้กฎ",
    editTitle: "แก้กฎ {scope}",
    policy: "นโยบายเป็นคำพูด",
    policyHint: "เช่น \"งานแอร์ให้ทีม AC วันละไม่เกิน 5 งาน\" — ระบบแปลงเป็นกฎแล้วแสดงให้ตรวจ",
    team: "ทีม",
    save: "บันทึกกฎ",
    saved: "บันทึกกฎแล้ว",
    close: "ปิดกฎ",
    closeAction: "ปิดกฎมอบหมาย",
    closeAffects: "งานใหม่จะไม่ถูกแจกอัตโนมัติอีก ต้องมอบหมายเอง",
    closeKeeps: "ตั้งใหม่ได้ทุกเมื่อ · กฎเดิมยังอยู่ในประวัติ",
    closed: "ปิดกฎแล้ว งานใหม่จะไม่ถูกแจกอัตโนมัติ",
    notUnderstood: "ยังแปลงนโยบายเป็นกฎไม่ได้: {problems}",
  },
  company: {
    readOnly: "ดูได้อย่างเดียว ต้องมีสิทธิ์จัดการการตั้งค่าบริษัทจึงจะแก้ไขได้",
    transferTitle: "โอนความเป็นเจ้าของร้าน",
    transferIntro: "เลือกสมาชิกที่จะรับเป็นเจ้าของคนใหม่ เขาต้องกด \"รับโอน\" ในเมนูทีมขายก่อนจึงจะมีผล และคุณจะกลายเป็นสมาชิกธรรมดา",
    pickMember: "เลือกสมาชิก",
    noOtherMembers: "ยังไม่มีสมาชิกคนอื่นในร้านที่จะรับโอนได้",
    request: "ส่งคำขอโอน",
    requested: "ส่งคำขอโอนแล้ว รอ {name} ยืนยัน",
    pending: "รอ {name} กดรับโอน",
    transferAction: "โอนความเป็นเจ้าของ",
    transferAffects: "เมื่ออีกฝ่ายยืนยัน คุณจะไม่ใช่เจ้าของร้านอีกต่อไป",
    transferNeedsAccept: "ยังไม่เปลี่ยนจนกว่าอีกฝ่ายจะกดยืนยัน · ยกเลิกก่อนหน้านั้นได้",
    confirm: "โอนความเป็นเจ้าของร้านให้ {name}? เมื่อเขายืนยัน คุณจะไม่ใช่เจ้าของอีกต่อไป",
  },
  menu: {
    transferOffer: "เจ้าของร้าน {shop} ขอโอนความเป็นเจ้าของร้านให้คุณ",
    accept: "รับโอน",
    accepted: "คุณเป็นเจ้าของร้านแล้ว — โหลดหน้าใหม่เพื่อเห็นสิทธิ์ทั้งหมด",
    acceptAction: "เข้าร่วมร้านนี้",
    acceptAffects: "เมนูและข้อมูลจะเปลี่ยนเป็นของร้านนี้",
    acceptKeeps: "สลับกลับไปร้านเดิมได้ด้วย \"เปลี่ยนร้าน\"",
    confirmAccept: "รับเป็นเจ้าของร้าน {shop}? คุณจะได้สิทธิ์ทั้งหมดและเจ้าของเดิมจะกลายเป็นสมาชิกธรรมดา",
  },
  groups: {
    title: "กลุ่มเซลส์",
    intro: "จัดพนักงานขายเป็นกลุ่ม เพื่อดูยอดและแบ่งลูกค้าเป็นทีม (ในแชท: \"สร้างกลุ่มเซลส์ ทีมเหนือ\")",
    newGroup: "ชื่อกลุ่มใหม่",
    create: "สร้างกลุ่ม",
    created: "สร้างกลุ่มแล้ว",
    empty: "ยังไม่มีกลุ่มเซลส์",
    addMember: "เพิ่มสมาชิกเข้ากลุ่ม",
    pickMember: "เลือกสมาชิก",
    allIn: "สมาชิกทุกคนอยู่ในกลุ่มนี้แล้ว",
    deleteGroup: "ลบกลุ่ม",
    deleteAffects: "สมาชิกยังอยู่ในร้าน แค่ไม่อยู่ในกลุ่มนี้",
    deleteButton: "ลบกลุ่ม",
    removeAction: "เอาออกจากกลุ่ม",
    removeKeeps: "เพิ่มกลับเข้ากลุ่มได้ทุกเมื่อ",
    confirmDelete: "ลบกลุ่มนี้ใช่ไหม สมาชิกจะยังอยู่ในร้าน แค่ไม่อยู่ในกลุ่มนี้",
    confirmRemove: "เอาสมาชิกคนนี้ออกจากกลุ่มใช่ไหม",
  },
  related: {
    movedButOldKept: "สร้างนัดใหม่แล้ว แต่ยกเลิกนัดเดิมไม่สำเร็จ — กด \"ยกเลิกนัด\" ที่นัดเดิมด้วย",
    needsFollowupCreate: "ต้องมีสิทธิ์ตั้งรายการติดตาม",
    needsNoteCreate: "ต้องมีสิทธิ์เพิ่มบันทึก",
  },
  roles: {
    readOnly: "ดูได้อย่างเดียว ต้องมีสิทธิ์จัดการบทบาทจึงจะแก้ไขได้",
  },
};

const en: typeof th = {
  errors: {
    suspended: "The shop is suspended — nothing new can be saved",
    forbidden: "You do not have permission for this",
    notFound: "This record no longer exists",
    conflict: "Not possible in the current state",
    invalid: "Some of the data is not valid — check the fields",
    failed: "The action failed ({status})",
    readOnly: "Read-only — the \"{permission}\" permission is needed to edit",
    showingLatest: "Showing the latest {count}",
  },
  reasons: {
    deal_has_no_products: "This deal has no products yet — add one to the deal first",
    quote_transition_not_allowed: "The quote cannot move to that status from here",
    company_incomplete: "The document cannot be issued yet — fill in the company profile: {fields}",
    already_issued: "This quote already has a document; confirm again to issue a new one",
    transfer_already_pending: "An ownership transfer is already waiting",
    transfer_target_is_self: "Pick another member as the new owner",
    not_owner: "Only the current owner can transfer ownership",
    not_nominee: "This transfer was not addressed to you",
    transfer_not_pending: "This transfer has already been used",
    member_not_active: "That member is no longer in the shop",
    already_exists: "That name already exists",
    duplicate: "This already exists ({code})",
    dispatch_blocked: "Cannot dispatch yet — missing: {fields}",
    tenant_suspended: "The shop is suspended — nothing new can be saved",
    reason_required: "A reason is required",
    staff_only: "Shop staff only",
    invoice_state: "The invoice is not in a state that allows this (issue it before recording a payment; a receipt needs full payment)",
    payment_invalid: "The amount is not valid — it must be above 0 and no more than the outstanding balance",
  },
  customers: {
    lastNameAndPhone: "A last name and a phone number are required (the first name is optional)",
  },
  deals: {
    finalStage: "This deal is closed — a final stage",
    lostReasonTitle: "Deal lost — why?",
    lostReasonHint: "Optional, but a reason shows what keeps losing deals",
    confirmLost: "Mark as lost",
    needsQuoteCreate: "Needs the create-quotes permission",
  },
  quotes: {
    markSent: "Sent to the customer",
    markExpired: "Expired",
    issueBeforeSend: "Issue the document first, then mark it as sent",
    final: "This quote is closed; its status can no longer change",
    needsUpdate: "Needs the edit-quotes permission to issue or change status",
  },
  tickets: {
    latestOnly: "Open jobs only (up to {count} per status)",
  },
  warranties: {
    serialSearch: "Search by serial",
    serialSearchHint: "Type the full serial number, then search",
    search: "Search",
    clearSearch: "Show all",
    serialNotFound: "No unit with serial {serial} at this shop",
  },
  products: {
    codeLocked: "The product code cannot be changed — a new code is a new product; add one instead",
    readOnly: "Read-only list; the manage-products permission is needed to add or edit",
    archive: "Archive",
    archiveAction: "Archive product",
    archiveMany: "Archive ({n})",
    archiveManyTarget: "{n} products",
    archiveKeepsDeals: "Deals and quotes that carry this product keep their lines",
    archiveKeepsRow: "Archived, not erased · leaves the list and the picker when adding a line to a deal",
    archived: "Archived {name} ({code}) · existing deals are untouched",
  },
  transfer: {
    ownerTitle: "Owner",
    currentOwner: "Looked after by",
    nobody: "Nobody yet",
    someoneElse: "A member no longer on the roster",
    handTo: "Hand to",
    pickColleague: "Pick a colleague…",
    hint: "Pick a name and you will be asked to confirm · in chat: \"transfer customer Somchai to Somying\"",
    action: "Hand to {name}",
    affects: "{name} is told on LINE and sees this record as theirs",
    reversible: "Can be handed back any time from this same field",
    done: "{label} handed to {name}",
    denied: "You do not have the reassign-records permission",
    many: "Change owner ({n})",
    manyTitle: "Change owner of {n} records",
    manyHint: "Every chosen record goes to the same person · they are told on LINE",
    manyConfirm: "Hand {n} records to {name}",
  },
  satisfaction: {
    title: "Satisfaction",
    intro: "What customers scored after a repair (1 = poor · 3 = excellent) — the survey goes out by itself when a job closes",
    period: "Period",
    days30: "30 days",
    days90: "90 days",
    days365: "12 months",
    average: "Average score",
    outOf: "out of 3",
    answered: "Answered",
    pending: "Waiting",
    responseRate: "Response rate",
    responseHint: "{answered} answered of {sent} sent",
    distribution: "Spread",
    byTechnician: "By technician",
    technician: "Technician",
    answers: "Answers",
    noTechnicians: "No answers that name a technician yet (jobs nobody was assigned to)",
    recent: "Latest answers",
    noAnswers: "No answers in this period",
    pendingNote: "{n} still waiting for the customer",
    comment: "Comment",
    noPermission: "Your account cannot view reports yet — ask the owner for the \"view reports\" permission",
    chatHint: "In chat: \"satisfaction score\" or \"satisfaction for technician Somsak\"",
  },
  rules: {
    title: "Automatic assignment rule",
    intro: "New repair jobs and new customers are handed to a team by this rule · set it in chat with \"assignment rule …\" or type the policy below",
    none: "No rule — new work is assigned by hand",
    scopeTechnician: "Technician rule (repair jobs)",
    scopeSales: "Sales rule (new customers)",
    scope: "Scope",
    conditions: "Conditions",
    noConditions: "No conditions — applies to every job",
    conditionLine: "if {field} {operator} {value} → team {team}",
    strategy: "How someone is picked",
    strategies: { least_load: "whoever has the fewest jobs", round_robin: "take turns", first_available: "the first one free" },
    capacity: "Daily cap",
    noCapacity: "No limit",
    capacityLine: "{n} a day ({mode})",
    hardBlock: "never exceed",
    softWarn: "allowed, but flagged",
    fields: { "product.category": "product category", "product.name": "product name", "customer.stage": "customer stage", "customer.source": "customer source" },
    operators: { equals: "is", not_equals: "is not", in: "is one of", contains: "contains", gt: "more than", gte: "at least", lt: "less than", lte: "at most" },
    edit: "Edit rule",
    editTitle: "Edit the {scope}",
    policy: "Policy in words",
    policyHint: "e.g. \"AC jobs go to team AC, at most 5 a day\" — it is turned into a rule and shown back",
    team: "Team",
    save: "Save rule",
    saved: "Rule saved",
    close: "Switch off",
    closeAction: "Switch the rule off",
    closeAffects: "New work will no longer be handed out automatically",
    closeKeeps: "Can be set again any time · the old rule stays in the history",
    closed: "Rule switched off — new work is assigned by hand",
    notUnderstood: "Could not turn that into a rule: {problems}",
  },
  company: {
    readOnly: "Read-only; the manage-company-settings permission is needed to edit",
    transferTitle: "Transfer shop ownership",
    transferIntro: "Pick the member who will become the new owner. It takes effect when they tap \"Accept\" on the sales menu, and you become an ordinary member.",
    pickMember: "Pick a member",
    noOtherMembers: "There is no other member in the shop to hand over to",
    request: "Send transfer request",
    requested: "Transfer requested — waiting for {name} to accept",
    pending: "Waiting for {name} to accept",
    transferAction: "Transfer ownership",
    transferAffects: "Once they accept, you are no longer the owner of this shop",
    transferNeedsAccept: "Nothing changes until they accept · you can cancel before that",
    confirm: "Transfer ownership of the shop to {name}? Once they accept, you are no longer the owner.",
  },
  menu: {
    transferOffer: "The owner of {shop} wants to hand ownership of the shop to you",
    accept: "Accept",
    accepted: "You are now the owner — reload to see every permission",
    acceptAction: "Join this shop",
    acceptAffects: "The menu and the records become this shop's",
    acceptKeeps: "Switch back with \"change shop\"",
    confirmAccept: "Become the owner of {shop}? You get every permission and the previous owner becomes an ordinary member.",
  },
  groups: {
    title: "Sales groups",
    intro: "Group salespeople to compare figures and share customers as a team (in chat: \"create sales group North\")",
    newGroup: "New group name",
    create: "Create group",
    created: "Group created",
    empty: "No sales groups yet",
    addMember: "Add a member",
    pickMember: "Pick a member",
    allIn: "Every member is already in this group",
    deleteGroup: "Delete group",
    deleteAffects: "Members stay in the shop, just not in this group",
    deleteButton: "Delete group",
    removeAction: "Remove from the group",
    removeKeeps: "They can be added back at any time",
    confirmDelete: "Delete this group? The members stay in the shop, just not in this group",
    confirmRemove: "Remove this member from the group?",
  },
  related: {
    movedButOldKept: "The new appointment was made, but the old one could not be cancelled — tap \"cancel\" on it",
    needsFollowupCreate: "Needs the create-follow-ups permission",
    needsNoteCreate: "Needs the add-notes permission",
  },
  roles: {
    readOnly: "Read-only; the manage-roles permission is needed to edit",
  },
};

export type SalesText = typeof th;

export function useSalesText(): SalesText {
  const { locale } = useLanguage();
  return locale === "en" ? en : th;
}
