"""Thai message -> JSON action — Master Spec 4.6/4.7.

The permission gate is NOT here. The model is told which permission keys the
caller holds so it can answer usefully ("you can't do that, but here's what you
can"), but a model that hallucinates an action it was told it lacks must still
be stopped by the real check in the Data Tier. Prompt text is guidance; it is
not an authorization boundary, and Principle #10's gate stays where it is.
"""
from __future__ import annotations

import json
import logging

from .client import AIUnavailable, complete

log = logging.getLogger(__name__)

# Shown to the user when every provider failed (4.7). Deliberately plain: no
# blame, no jargon, no invented detail about what went wrong.
#
# Phase 5: this string is produced before any model call succeeds, so it cannot
# come from the model — it has to exist per-locale in our own code.
UNAVAILABLE_REPLY_BY_LOCALE = {
    "th": "ขออภัย ระบบไม่พร้อมใช้งานชั่วคราว กรุณาลองใหม่อีกครั้ง",
    "en": "Sorry — the service is temporarily unavailable. Please try again.",
}
DEFAULT_LOCALE = "th"

# Kept for callers that predate Phase 5's language plumbing.
UNAVAILABLE_REPLY = UNAVAILABLE_REPLY_BY_LOCALE[DEFAULT_LOCALE]


def unavailable_reply(language: str = DEFAULT_LOCALE) -> str:
    """Fall back to Thai for an unknown locale — the product is Thai-first."""
    return UNAVAILABLE_REPLY_BY_LOCALE.get(
        (language or "").lower(), UNAVAILABLE_REPLY_BY_LOCALE[DEFAULT_LOCALE]
    )

INTENT_SYSTEM_PROMPT = """You are an intent parser for a CRM system.
Convert the user's message into a JSON action.

User context:
- chann_uid: {chann_uid}
- role: {role}
- license_id: {license_id}
- language: {language}

Permission keys this user holds: {permission_keys}

Return ONLY a JSON object, no prose and no markdown fences.

Shape:
{{"action": "...", "entity": "...", "fields": {{}}, "missing": []}}

Rules:
- If required information is missing, list the missing field names in "missing".
- If the user's permission keys do not cover the requested action, return
  {{"action": "suggest", "suggestions": [...]}} listing things they may do instead.
- Never invent field values the user did not provide.
- Any human-readable text you produce (suggestions, and the names of missing
  fields as shown to the user) MUST be written in {language_name}.
  Machine-facing values — action, entity, and field keys — stay in English
  regardless of language, because downstream code matches on them.

Special case — the user's OWN contact details (their name, phone number,
email, or address, e.g. "แก้เบอร์เป็น 08x-xxx-xxxx", "เปลี่ยนอีเมลเป็น..."):
use entity="profile", action="update", and put only the changed value(s) in
"fields" using exactly these keys: first_name, last_name, phone, email,
address. Do not use "profile" for anyone else's details — only the current
user's own.

Entity field shapes (Phase 9 CRM — use EXACTLY these field names, never
invent additional ones, because the entity another party's fields describes
does not exist anywhere else the model can check against):

- entity="customer" — a lead or contact record.
  action="create": fields may include first_name, last_name, phone, email,
    address, notes. last_name AND phone are BOTH required — a first name
    alone is not enough to reliably identify someone later, and phone is
    how staff follow up. If either is missing, list it in "missing"
    (e.g. ["last_name"], ["phone"], or both) rather than creating anyway.
  action="update": the message names an EXISTING customer by name (never by
    an id the user would never type) — put that name in fields.target_name,
    and put only the changed value(s) under first_name/last_name/phone/
    email/address/notes. Example: "แก้เบอร์ลูกค้าสมชายเป็น 0899999999" ->
    fields={{"target_name": "สมชาย", "phone": "0899999999"}}.
  action="promote": confirming a Lead as a real Contact, e.g. "ยืนยันลูกค้า
    สมชาย" or "สมชายตกลงซื้อแล้ว". fields={{"target_name": "สมชาย"}}, no
    other fields.

- entity="deal" — a sales opportunity tied to an existing customer.
  action="create": fields={{"target_name": "<customer name>", "notes":
    "..." (optional)}}. target_name is required — a deal cannot be created
    without saying which customer it is for.
  A deal's own reference code (e.g. "D-2026-0001") is generated by the
  system, never asked from the user and never invented by you.

- entity="product" — an item in this tenant's own product catalogue
  (Phase 7 master data), NOT a deal's line item.
  action="create" or "update" (treat both the same — creating a product
    that already exists by product_id updates it instead of erroring):
    fields may include product_id, product_name, sku, category, unit_price,
    description. product_id and product_name are both required — list
    either as "missing" if absent. product_id is a short business code the
    user gives (e.g. "FAN001"), never one you invent.

- entity="quote" — a price quote generated from an existing deal, e.g.
  "สร้างใบเสนอราคาจากดีล D-2026-0001" or "ทำใบเสนอราคาให้ดีล D-2026-0001".
  action="create": fields={{"deal_code": "D-2026-0001"}}. deal_code is
    required — a quote is always created FROM a specific existing deal,
    never invented, and its own code (e.g. "Q-2026-0001") is generated by
    the system afterward, never asked from the user or invented by you.

- entity="note" — a short remark about a customer, deal or quote that is
  neither a data field to change nor a request for anything else. Examples:
  "ลูกค้าสนใจเรื่องการซื้อบ้าน", "ลูกค้าขอส่วนลด 10%", "รอลูกค้าตอบกลับเรื่องสัญญา".
  action="create": fields={{"body": "<the remark, in the user's own words>",
    "entity_code": "C-2026-0001"}}. entity_code is the record's own code
    (starts with C-/D-/Q-) if the user gave one; OMIT the key entirely if
    they did not — do not guess one and do not put it in "missing", since
    the system may already know which record the conversation is about.
  Never choose entity="note" for a sentence that is actually asking to
  change a named field (a phone number, a stage, a price) — those stay
  entity="customer"/"deal"/etc. with action="update". note is for
  free-text observations with no field structure at all.
"""

# Appended only when the previous turn left a question hanging. Spec 6.4
# describes parsing one message in isolation, which silently assumes every
# message is self-contained — but the bot itself creates messages that are
# NOT: it asks "what is the phone number?", and the honest human answer is a
# bare "0812345678" with no verb, no entity, and no way to parse it alone.
PENDING_PROMPT_BLOCK = """

There is an action ALREADY IN PROGRESS from the previous message:
- action: {p_action}
- entity: {p_entity}
- values already collected: {p_fields}
- still waiting for: {p_missing}

The user's new message is most likely their answer to what was being waited
for. If it is, return that SAME action and entity, and put the value they
just gave into "fields" under the field name that was waited for. Return a
different action/entity ONLY if the user has clearly changed the subject.
"""

# Spelled out for the model rather than passing a bare code: "th" is far more
# ambiguous in a prompt than "Thai".
LANGUAGE_NAMES = {"th": "Thai", "en": "English"}


def build_prompt(
    *,
    chann_uid: str,
    role: str,
    license_id: str,
    permission_keys: list[str] | frozenset[str],
    language: str = "th",
    pending: dict | None = None,
) -> str:
    keys = sorted(permission_keys)
    lang = (language or DEFAULT_LOCALE).lower()
    prompt = INTENT_SYSTEM_PROMPT.format(
        chann_uid=chann_uid,
        role=role,
        license_id=license_id,
        language=lang,
        language_name=LANGUAGE_NAMES.get(lang, LANGUAGE_NAMES[DEFAULT_LOCALE]),
        permission_keys=", ".join(keys) if keys else "(none)",
    )
    if pending:
        prompt += PENDING_PROMPT_BLOCK.format(
            p_action=pending.get("action") or "?",
            p_entity=pending.get("entity") or "?",
            p_fields=json.dumps(pending.get("fields") or {}, ensure_ascii=False),
            p_missing=", ".join(pending.get("missing") or []) or "(nothing)",
        )
    return prompt


def parse_intent_json(raw: str) -> dict:
    """Extract the JSON object from a model reply.

    Tolerates markdown fences and leading prose because models emit them even
    when told not to, but does not tolerate a shape the caller can't rely on:
    a reply without a usable "action" raises rather than returning a dict that
    looks fine until something downstream reads .get("action") and gets None.
    """
    text = (raw or "").strip()

    if text.startswith("```"):
        # ```json ... ``` — drop the fence line and everything after the close.
        text = text.split("\n", 1)[1] if "\n" in text else ""
        if "```" in text:
            text = text.split("```", 1)[0]
        text = text.strip()

    if not text.startswith("{"):
        start = text.find("{")
        end = text.rfind("}")
        if start == -1 or end <= start:
            raise AIUnavailable("model reply contained no JSON object")
        text = text[start : end + 1]

    try:
        parsed = json.loads(text)
    except json.JSONDecodeError as exc:
        raise AIUnavailable(f"model reply was not valid JSON: {exc}") from exc

    if not isinstance(parsed, dict):
        raise AIUnavailable("model reply was not a JSON object")

    action = parsed.get("action")
    if not isinstance(action, str) or not action.strip():
        raise AIUnavailable("model reply had no usable 'action'")

    parsed.setdefault("entity", None)
    parsed.setdefault("fields", {})
    parsed.setdefault("missing", [])
    if not isinstance(parsed["fields"], dict):
        parsed["fields"] = {}
    if not isinstance(parsed["missing"], list):
        parsed["missing"] = []
    return parsed


async def parse_intent(
    *,
    message: str,
    chann_uid: str,
    role: str,
    license_id: str,
    permission_keys: list[str] | frozenset[str],
    language: str = "th",
    client=None,
    pending: dict | None = None,
) -> dict:
    """Parse one user message. Raises AIUnavailable; never returns a half-result."""
    system_prompt = build_prompt(
        chann_uid=chann_uid,
        role=role,
        license_id=license_id,
        permission_keys=permission_keys,
        language=language,
        pending=pending,
    )
    raw = await complete(
        system_prompt=system_prompt,
        user_message=message,
        thinking=False,          # 4.3: chat tier runs with thinking OFF
        client=client,
    )
    return parse_intent_json(raw)
