/** Phase 18 — every word the Platform Admin console shows, in one place.
 *  The console is the operator's own tool (Thai), not a tenant surface, so it
 *  does not go through the LIFF dictionary — but the words still live outside
 *  the pages, where the no-hardcoded-Thai check expects them. */
export const ADMIN = {
  brand: "Chann CRM AI",
  brandSub: "Platform Admin",
  nav: {
    label: "เมนูหลัก",
    collapse: "ย่อเมนู",
    expand: "ขยายเมนู",
    tenants: "ร้านค้า (tenants)",
    audit: "Audit ข้ามร้าน",
    pdpa: "คำขอ PDPA",
  },
  signedInAs: "เข้าใช้เป็น",
  logout: "ออกจากระบบ",
  status: {
    active: "ใช้งาน",
    trial: "ทดลองใช้",
    suspended: "ระงับ",
    deleted: "ลบแล้ว",
    pending: "รอดำเนินการ",
    processing: "กำลังทำ",
    completed: "เสร็จแล้ว",
    rejected: "ปฏิเสธ",
  } as Record<string, string>,
  login: {
    title: "Platform Admin",
    intro: "คอนโซลผู้ดูแลแพลตฟอร์ม Chann CRM AI",
    username: "ชื่อผู้ใช้",
    password: "รหัสผ่าน",
    submit: "เข้าสู่ระบบ",
    working: "กำลังเข้าสู่ระบบ…",
    invalid: "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง",
    locked: (until: string) => `บัญชีถูกล็อกชั่วคราวจากการใส่รหัสผ่านผิดหลายครั้ง ล็อกถึง ${until} — อย่าลองซ้ำก่อนเวลานี้`,
    lockedUnknown: "บัญชีถูกล็อกชั่วคราวจากการใส่รหัสผ่านผิดหลายครั้ง ลองใหม่ใน 15 นาที",
    unavailable: "เข้าสู่ระบบไม่ได้ในขณะนี้ ลองใหม่อีกครั้ง",
    sessionExpired: "เซสชันหมดอายุ กรุณาเข้าสู่ระบบอีกครั้ง",
  },
  tenants: {
    title: "ร้านค้าทั้งหมด",
    intro: "ทุก tenant บนแพลตฟอร์ม พร้อมขนาดการใช้งาน กดชื่อร้านเพื่อดูสมาชิก ระงับ หรือโอนสิทธิ์เจ้าของ",
    summary: "สรุป",
    filteredSummary: "ตัวเลขสรุปนับเฉพาะร้านที่ตรงกับตัวกรองด้านล่าง",
    total: "ร้านทั้งหมด",
    active: "ใช้งาน",
    trialShort: "ทดลอง",
    suspended: "ระงับ",
    deletedShort: "ลบแล้ว",
    members: "สมาชิกรวม",
    openTickets: "งานค้างรวม",
    search: "ค้นหา",
    searchPlaceholder: "ชื่อร้าน / รหัสร้าน / license",
    statusLabel: "สถานะ",
    anyStatus: "ทุกสถานะ",
    searchButton: "ค้นหา",
    clear: "ล้างตัวกรอง",
    empty: "ไม่พบร้านตามเงื่อนไข",
    columns: {
      shop: "ร้าน",
      status: "สถานะ",
      owner: "เจ้าของ",
      members: "สมาชิก",
      customers: "ลูกค้า",
      ticketsOpen: "งาน (ค้าง)",
      deals: "ดีล",
      lastActivity: "ใช้งานล่าสุด",
      created: "สร้างเมื่อ",
    },
  },
  tenant: {
    crumb: "ร้านค้า",
    shopCode: "รหัสร้าน",
    metrics: { members: "สมาชิก", customers: "ลูกค้า", tickets: "งาน", open: "ค้าง", deals: "ดีล" },
    info: "ข้อมูลร้าน",
    owner: "เจ้าของ",
    legalName: "ชื่อนิติบุคคล",
    phone: "โทร",
    email: "อีเมล",
    trialUntil: "วันหมดอายุ",
    deletedAt: "ลบเมื่อ",
    adminNotes: "บันทึกของผู้ดูแล",
    created: "สร้างเมื่อ",
    lastActivity: "ใช้งานล่าสุด",
    edit: {
      open: "แก้ไขข้อมูล",
      cancel: "ยกเลิก",
      save: "บันทึก",
      saving: "กำลังบันทึก…",
      saved: "บันทึกแล้ว",
      failed: "บันทึกไม่สำเร็จ",
      companyName: "ชื่อร้าน",
      legalName: "ชื่อนิติบุคคล",
      phone: "โทร",
      email: "อีเมล",
      address: "ที่อยู่",
      taxId: "เลขผู้เสียภาษี",
      trialUntil: "วันหมดอายุ",
      trialHint: "ใช้กับทั้งทดลองใช้และใช้งานอยู่ · เว้นว่าง = ไม่มีวันหมดอายุ · ระบบเตือนเจ้าของร้านล่วงหน้า 3 และ 1 วัน และระงับอัตโนมัติเมื่อถึงกำหนด",
      adminNotes: "บันทึกของผู้ดูแล (ร้านไม่เห็น)",
      adminNotesHint: "เช่น ชำระแล้วถึงเมื่อไร ติดต่อใคร — เห็นเฉพาะในคอนโซลนี้",
      status: "สถานะ",
      statusHint: "ทดลองใช้ → ใช้งาน เมื่อร้านชำระ/เปิดใช้จริง; การระงับใช้ปุ่มด้านขวา; ร้านที่ลบแล้วกู้คืนได้โดยเลือกสถานะกลับเป็นทดลองใช้/ใช้งาน",
      aiChartQuota: "โควตากราฟ AI ต่อเดือน",
      aiChartQuotaHint: "จำนวนกราฟแบบสร้างเองที่ร้านนี้ขอได้ต่อเดือน · เว้นว่าง = ค่าเริ่มต้น 30 · 0 = ปิดกราฟสร้างเอง · กราฟสำเร็จรูปและรายงานตัวหนังสือไม่นับโควตา",
      aiChartUsed: "ใช้ไปเดือนนี้",
      aiChartDefault: "30 (ค่าเริ่มต้น)",
      aiChartQuotaNumber: "โควตาต้องเป็นตัวเลข 0 ขึ้นไป",
      companyNameRequired: "ต้องมีชื่อร้าน",
      noChanges: "ไม่มีอะไรเปลี่ยน",
      address_shown: "ที่อยู่",
      taxId_shown: "เลขผู้เสียภาษี",
    },
    membersTitle: "สมาชิก",
    membersEmpty: "ยังไม่มีสมาชิก",
    memberColumns: { name: "ชื่อ", uid: "Chann UID", channel: "ช่องทาง", role: "บทบาท", status: "สถานะ", joined: "เข้าร่วม", actions: "จัดการ" },
    ownerTag: "(owner)",
    members: {
      channel: { sales: "Sales OA", technician: "ช่าง OA" } as Record<string, string>,
      saveRole: "บันทึกบทบาท",
      remove: "ถอดออก",
      reactivate: "เปิดใช้อีกครั้ง",
      move: "ย้ายไปบริษัท…",
      moveTitle: "ย้ายสมาชิกไปบริษัทอื่น",
      moveTarget: "บริษัทปลายทาง",
      moveRole: "บทบาทที่บริษัทใหม่",
      pickTenant: "เลือกบริษัท",
      confirmMove: "ยืนยันย้าย",
      cancel: "ยกเลิก",
      ownerLocked: "เจ้าของร้าน: เปลี่ยนได้ผ่าน break-glass เท่านั้น",
      confirmRole: (name: string, role: string) => `เปลี่ยนบทบาทของ ${name} เป็น "${role}"?`,
      confirmRemove: (name: string) => `ถอด ${name} ออกจากร้านนี้? ถ้าเป็นช่าง งานที่ค้างจะกลับเข้าคิว`,
      confirmReactivate: (name: string) => `เปิดใช้สมาชิก ${name} อีกครั้ง?`,
      confirmMoveText: (name: string, company: string, role: string) =>
        `ย้าย ${name} ไปยัง ${company} ในบทบาท "${role}"? สมาชิกจะถูกถอดจากร้านนี้และเพิ่มที่ร้านใหม่ (บันทึก audit ทั้งสองร้าน)`,
      roleSaved: "เปลี่ยนบทบาทแล้ว",
      removed: "ถอดสมาชิกแล้ว",
      unassigned: (n: number) => `คืนงานเข้าคิว ${n} งาน`,
      reactivated: "เปิดใช้สมาชิกแล้ว",
      moved: (company: string) => `ย้ายไป ${company} แล้ว`,
      failed: "ทำรายการไม่สำเร็จ",
      working: "กำลังทำ…",
    },
    auditTitle: "Audit ล่าสุดของร้านนี้",
    auditEmpty: "ยังไม่มีรายการ",
    auditColumns: { when: "เมื่อ", actor: "ผู้กระทำ", action: "การกระทำ", changes: "สิ่งที่แก้", cross: "ข้ามร้าน" },
    yes: "ใช่",
    actions: {
      title: "การจัดการ",
      reopen: "เปิดใช้งานอีกครั้ง",
      suspend: "ระงับร้านนี้",
      working: "กำลังทำ…",
      note: "ระงับ = อ่านได้อย่างเดียว ข้อมูลไม่ถูกลบ เปิดกลับได้ทุกเมื่อ",
      confirmSuspend: "ระงับร้านนี้? สมาชิกทุกคนจะทำรายการใหม่ผ่านแชทและหน้าจอไม่ได้จนกว่าจะเปิดใช้งานอีกครั้ง",
      confirmReopen: "เปิดใช้งานร้านนี้อีกครั้ง?",
      confirmReopenExpired: "วันหมดอายุของร้านนี้ผ่านไปแล้ว การเปิดใช้งานจะต่ออายุให้ 30 วันจากวันนี้ ยืนยัน?",
      suspended: "ระงับร้านแล้ว",
      reopened: "เปิดใช้งานแล้ว",
      reopenedExtended: "เปิดใช้งานแล้ว และต่ออายุให้ 30 วัน",
      subscriptionTitle: "ต่ออายุการใช้งาน",
      expiresOn: "วันหมดอายุ",
      noExpiry: "ไม่มีวันหมดอายุ",
      expired: "หมดอายุแล้ว",
      extend30: "ต่ออายุ +30 วัน",
      extend365: "+365 วัน",
      confirmExtend: (days: number) => `ต่ออายุ ${days} วัน (นับจากวันหมดอายุเดิม หรือวันนี้ถ้าหมดอายุแล้ว)? ร้านที่ถูกระงับจะเปิดใช้งานอีกครั้ง`,
      extended: (days: number, until: string) => `ต่ออายุ ${days} วันแล้ว — หมดอายุ ${until}`,
      extendNote: "นับต่อจากวันหมดอายุเดิม ถ้าหมดอายุแล้วนับจากวันนี้ · ร้านที่ถูกระงับจะกลับมาใช้งาน · ร้านที่ลบแล้วต้องกู้คืนก่อน",
      deletedNote: "ร้านนี้ถูกลบแล้ว (สมาชิกทุกคนถูกถอด) กู้คืนได้จาก \"แก้ไขข้อมูล\" โดยเลือกสถานะกลับเป็นทดลองใช้หรือใช้งาน",
      failed: "ทำรายการไม่สำเร็จ ลองใหม่อีกครั้ง",
      reason: (why: string) => `เหตุผล: ${why}`,
      breakGlassTitle: "Break-glass: โอนสิทธิ์เจ้าของ",
      newOwner: "เจ้าของคนใหม่",
      noCandidates: "ไม่มีสมาชิกอื่นให้เลือก",
      pickMember: "เลือกสมาชิก",
      transfer: "โอนสิทธิ์ (ฉุกเฉิน)",
      transferring: "กำลังโอน…",
      confirmTransfer: (name: string) =>
        `โอนสิทธิ์เจ้าของร้านให้ ${name} (กรณีฉุกเฉิน)? เจ้าของเดิมจะกลายเป็น admin และระบบจะบันทึก audit ข้ามร้าน`,
      transferred: (name: string) => `โอนสิทธิ์เจ้าของให้ ${name} แล้ว และแจ้งทาง LINE`,
      transferFailed: "โอนสิทธิ์ไม่สำเร็จ ตรวจว่าคนที่เลือกยังเป็นสมาชิกที่ใช้งานอยู่",
    },
    delete: {
      title: "ลบบริษัท",
      intro: "ลบแบบปกติ = สถานะ \"ลบแล้ว\" สมาชิกทุกคนถูกถอด ร้านหายจากรายการ กู้คืนได้ · ลบถาวร (purge) = ลบข้อมูลทุกอย่างของร้านออกจากระบบ ย้อนกลับไม่ได้",
      typeCode: (code: string) => `พิมพ์รหัสร้าน ${code} เพื่อยืนยัน`,
      codePlaceholder: "รหัสร้าน",
      purge: "ลบถาวร (purge) — ลบข้อมูลทั้งหมด ย้อนกลับไม่ได้",
      purgeNeedsBreakGlass: "การลบถาวรต้องมีสิทธิ์ break-glass",
      button: "ลบบริษัท",
      buttonPurge: "ลบบริษัทถาวร",
      working: "กำลังลบ…",
      confirmSoft: (name: string) => `ลบ ${name}? สมาชิกทุกคนจะถูกถอด และร้านจะหายจากรายการ (กู้คืนได้ภายหลัง)`,
      confirmPurge: (name: string) => `ลบ ${name} ถาวร? ลูกค้า งาน ดีล เอกสาร และสมาชิกทั้งหมดจะถูกลบออกจากระบบ ย้อนกลับไม่ได้`,
      deleted: "ลบบริษัทแล้ว (กู้คืนได้จากตัวกรองสถานะ \"ลบแล้ว\")",
      purged: (rows: number) => `ลบบริษัทถาวรแล้ว (${rows} แถว)`,
      failed: "ลบไม่สำเร็จ",
      alreadyDeleted: "ร้านนี้ถูกลบแล้ว — เลือก \"ลบถาวร\" เพื่อลบข้อมูลทั้งหมด หรือกู้คืนจาก \"แก้ไขข้อมูล\"",
    },
  },
  audit: {
    title: "Audit ข้ามร้าน",
    intro: "ทุกการกระทำที่แพลตฟอร์มทำแทนร้าน (ระงับ, โอนสิทธิ์, PDPA) และรายการภายในร้านเมื่อกรองตามร้าน",
    scope: "ขอบเขต",
    scopeCross: "เฉพาะข้ามร้าน (cross_tenant)",
    scopeAll: "ทุกรายการ",
    tenant: "ร้าน (license id)",
    tenantPlaceholder: "uuid ของร้าน",
    actor: "ผู้กระทำ",
    anyActor: "ทุกประเภท",
    action: "การกระทำ",
    actionPlaceholder: "เช่น transfer, update, pdpa_erasure",
    filter: "กรอง",
    clear: "ล้าง",
    empty: "ไม่มีรายการตามเงื่อนไข",
    columns: { when: "เมื่อ", tenant: "ร้าน", actor: "ผู้กระทำ", action: "การกระทำ", changes: "สิ่งที่แก้", cross: "ข้ามร้าน" },
    yes: "ใช่",
  },
  pdpa: {
    title: "คำขอ PDPA",
    intro: "คำขอสำเนาข้อมูล ลบข้อมูล และถอนความยินยอมจากทุก OA คำขอจากแชท/หน้าจอทำเสร็จอัตโนมัติ ส่วนคำขอที่รอคือคำขอที่ผู้ดูแลสร้างแทน",
    total: "ทั้งหมด",
    pending: "รอดำเนินการ",
    statusLabel: "สถานะ",
    anyStatus: "ทุกสถานะ",
    filter: "กรอง",
    types: { erasure: "ลบข้อมูล", export: "สำเนาข้อมูล", consent_withdraw: "ถอนความยินยอม" } as Record<string, string>,
    createTitle: "สร้างคำขอแทนผู้ใช้ (ติดต่อมาทางอื่น)",
    uid: "Chann UID",
    type: "ประเภท",
    create: "สร้างคำขอ",
    creating: "กำลังสร้าง…",
    created: "สร้างคำขอแล้ว กด \"ดำเนินการ\" เมื่อยืนยันตัวตนของผู้ขอแล้ว",
    createFailed: "สร้างคำขอไม่สำเร็จ ตรวจ Chann UID",
    rejectReason: "เหตุผลที่ปฏิเสธ (จะบันทึกไว้กับคำขอ)",
    confirmErase: (uid: string) => `ลบข้อมูลของ ${uid} จากทุกร้าน? ย้อนกลับไม่ได้`,
    processed: "ดำเนินการแล้ว",
    rejected: "ปฏิเสธคำขอแล้ว",
    failed: "ทำรายการไม่สำเร็จ",
    process: "ดำเนินการ",
    reject: "ปฏิเสธ",
    close: "ปิดคำขอ",
    empty: "ยังไม่มีคำขอ",
    columns: { when: "ขอเมื่อ", who: "ผู้ขอ", type: "ประเภท", via: "ช่องทาง", status: "สถานะ", result: "ผล" },
  },
} as const;
