/** Phase 18 — every word the Platform Admin console shows, in one place.
 *  The console is the operator's own tool (Thai), not a tenant surface, so it
 *  does not go through the LIFF dictionary — but the words still live outside
 *  the pages, where the no-hardcoded-Thai check expects them. */
export const ADMIN = {
  brand: "Chann CRM AI",
  brandSub: "Platform Admin",
  nav: {
    label: "เมนูหลัก",
    tenants: "ร้านค้า (tenants)",
    audit: "Audit ข้ามร้าน",
    pdpa: "คำขอ PDPA",
  },
  signedInAs: "เข้าใช้เป็น",
  logout: "ออกจากระบบ",
  status: {
    active: "ใช้งาน",
    trial: "ทดลองใช้",
    suspended: "ระงับ",
    pending: "รอดำเนินการ",
    processing: "กำลังทำ",
    completed: "เสร็จแล้ว",
    rejected: "ปฏิเสธ",
  } as Record<string, string>,
  login: {
    title: "Platform Admin",
    intro: "คอนโซลผู้ดูแลแพลตฟอร์ม Chann CRM AI",
    username: "ชื่อผู้ใช้",
    password: "รหัสผ่าน",
    submit: "เข้าสู่ระบบ",
    working: "กำลังเข้าสู่ระบบ…",
    invalid: "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง",
    unavailable: "เข้าสู่ระบบไม่ได้ในขณะนี้ ลองใหม่อีกครั้ง",
  },
  tenants: {
    title: "ร้านค้าทั้งหมด",
    intro: "ทุก tenant บนแพลตฟอร์ม พร้อมขนาดการใช้งาน กดชื่อร้านเพื่อดูสมาชิก ระงับ หรือโอนสิทธิ์เจ้าของ",
    summary: "สรุป",
    total: "ร้านทั้งหมด",
    active: "ใช้งาน",
    trialShort: "ทดลอง",
    suspended: "ระงับ",
    members: "สมาชิกรวม",
    openTickets: "งานค้างรวม",
    search: "ค้นหา",
    searchPlaceholder: "ชื่อร้าน / รหัสร้าน / license",
    statusLabel: "สถานะ",
    anyStatus: "ทุกสถานะ",
    searchButton: "ค้นหา",
    clear: "ล้างตัวกรอง",
    empty: "ไม่พบร้านตามเงื่อนไข",
    columns: {
      shop: "ร้าน",
      status: "สถานะ",
      owner: "เจ้าของ",
      members: "สมาชิก",
      customers: "ลูกค้า",
      ticketsOpen: "งาน (ค้าง)",
      deals: "ดีล",
      lastActivity: "ใช้งานล่าสุด",
      created: "สร้างเมื่อ",
    },
  },
  tenant: {
    crumb: "ร้านค้า",
    shopCode: "รหัสร้าน",
    metrics: { members: "สมาชิก", customers: "ลูกค้า", tickets: "งาน", open: "ค้าง", deals: "ดีล" },
    info: "ข้อมูลร้าน",
    owner: "เจ้าของ",
    legalName: "ชื่อนิติบุคคล",
    phone: "โทร",
    email: "อีเมล",
    trialUntil: "ทดลองใช้ถึง",
    created: "สร้างเมื่อ",
    lastActivity: "ใช้งานล่าสุด",
    membersTitle: "สมาชิก",
    membersEmpty: "ยังไม่มีสมาชิก",
    memberColumns: { name: "ชื่อ", uid: "Chann UID", role: "บทบาท", status: "สถานะ", joined: "เข้าร่วม" },
    ownerTag: "(owner)",
    auditTitle: "Audit ล่าสุดของร้านนี้",
    auditEmpty: "ยังไม่มีรายการ",
    auditColumns: { when: "เมื่อ", actor: "ผู้กระทำ", action: "การกระทำ", changes: "สิ่งที่แก้", cross: "ข้ามร้าน" },
    yes: "ใช่",
    actions: {
      title: "การจัดการ",
      reopen: "เปิดใช้งานอีกครั้ง",
      suspend: "ระงับร้านนี้",
      working: "กำลังทำ…",
      note: "ระงับ = อ่านได้อย่างเดียว ข้อมูลไม่ถูกลบ เปิดกลับได้ทุกเมื่อ",
      confirmSuspend: "ระงับร้านนี้? สมาชิกทุกคนจะทำรายการใหม่ผ่านแชทและหน้าจอไม่ได้จนกว่าจะเปิดใช้งานอีกครั้ง",
      confirmReopen: "เปิดใช้งานร้านนี้อีกครั้ง?",
      suspended: "ระงับร้านแล้ว",
      reopened: "เปิดใช้งานแล้ว",
      failed: "ทำรายการไม่สำเร็จ ลองใหม่อีกครั้ง",
      breakGlassTitle: "Break-glass: โอนสิทธิ์เจ้าของ",
      newOwner: "เจ้าของคนใหม่",
      noCandidates: "ไม่มีสมาชิกอื่นให้เลือก",
      pickMember: "เลือกสมาชิก",
      transfer: "โอนสิทธิ์ (ฉุกเฉิน)",
      transferring: "กำลังโอน…",
      confirmTransfer: (name: string) =>
        `โอนสิทธิ์เจ้าของร้านให้ ${name} (กรณีฉุกเฉิน)? เจ้าของเดิมจะกลายเป็น admin และระบบจะบันทึก audit ข้ามร้าน`,
      transferred: (name: string) => `โอนสิทธิ์เจ้าของให้ ${name} แล้ว และแจ้งทาง LINE`,
      transferFailed: "โอนสิทธิ์ไม่สำเร็จ ตรวจว่าคนที่เลือกยังเป็นสมาชิกที่ใช้งานอยู่",
    },
  },
  audit: {
    title: "Audit ข้ามร้าน",
    intro: "ทุกการกระทำที่แพลตฟอร์มทำแทนร้าน (ระงับ, โอนสิทธิ์, PDPA) และรายการภายในร้านเมื่อกรองตามร้าน",
    scope: "ขอบเขต",
    scopeCross: "เฉพาะข้ามร้าน (cross_tenant)",
    scopeAll: "ทุกรายการ",
    tenant: "ร้าน (license id)",
    tenantPlaceholder: "uuid ของร้าน",
    actor: "ผู้กระทำ",
    anyActor: "ทุกประเภท",
    action: "การกระทำ",
    actionPlaceholder: "เช่น transfer, update, pdpa_erasure",
    filter: "กรอง",
    clear: "ล้าง",
    empty: "ไม่มีรายการตามเงื่อนไข",
    columns: { when: "เมื่อ", tenant: "ร้าน", actor: "ผู้กระทำ", action: "การกระทำ", changes: "สิ่งที่แก้", cross: "ข้ามร้าน" },
    yes: "ใช่",
  },
  pdpa: {
    title: "คำขอ PDPA",
    intro: "คำขอสำเนาข้อมูล ลบข้อมูล และถอนความยินยอมจากทุก OA คำขอจากแชท/หน้าจอทำเสร็จอัตโนมัติ ส่วนคำขอที่รอคือคำขอที่ผู้ดูแลสร้างแทน",
    total: "ทั้งหมด",
    pending: "รอดำเนินการ",
    statusLabel: "สถานะ",
    anyStatus: "ทุกสถานะ",
    filter: "กรอง",
    types: { erasure: "ลบข้อมูล", export: "สำเนาข้อมูล", consent_withdraw: "ถอนความยินยอม" } as Record<string, string>,
    createTitle: "สร้างคำขอแทนผู้ใช้ (ติดต่อมาทางอื่น)",
    uid: "Chann UID",
    type: "ประเภท",
    create: "สร้างคำขอ",
    creating: "กำลังสร้าง…",
    created: "สร้างคำขอแล้ว กด \"ดำเนินการ\" เมื่อยืนยันตัวตนของผู้ขอแล้ว",
    createFailed: "สร้างคำขอไม่สำเร็จ ตรวจ Chann UID",
    rejectReason: "เหตุผลที่ปฏิเสธ (จะบันทึกไว้กับคำขอ)",
    confirmErase: (uid: string) => `ลบข้อมูลของ ${uid} จากทุกร้าน? ย้อนกลับไม่ได้`,
    processed: "ดำเนินการแล้ว",
    rejected: "ปฏิเสธคำขอแล้ว",
    failed: "ทำรายการไม่สำเร็จ",
    process: "ดำเนินการ",
    reject: "ปฏิเสธ",
    close: "ปิดคำขอ",
    empty: "ยังไม่มีคำขอ",
    columns: { when: "ขอเมื่อ", who: "ผู้ขอ", type: "ประเภท", via: "ช่องทาง", status: "สถานะ", result: "ผล" },
  },
} as const;
