"""The chat corpus: 737 realistic utterances per intent per OA, tagged with
the linguistic pattern each one exercises (review of 6 Sep 2026, section
B). test_chat_corpus.py plays every one through the real router and fails
when any of them classifies worse than the committed baseline.

Each entry: (text, intent, tags) or a dict with "pre" (messages sent
first, to set up a pending state) and "ai" (the crafted model answer for
the sentences that legitimately go to the model). intent names are keys
of test_chat_corpus.SPEC; tags name the pattern.
"""
def _e(text, intent, tags, **kw):
    d = {"text": text, "intent": intent, "tags": tags.split()}
    d.update(kw)
    return d


CUSTOMER = [
    # ---- greetings / small talk -------------------------------------------------
    _e("สวัสดีคับ", "c.greet", "particle typo"),
    _e("หวัดดีจ้า", "c.greet", "particle"),
    _e("ดีค่ะ", "c.greet", "particle"),
    _e("สวัสดีครับผม", "c.greet", "particle"),
    _e("Hello ka", "c.greet", "karaoke mixed"),
    _e("sawasdee krub", "c.greet", "karaoke"),
    _e("หวัดดีครับ สอบถามหน่อยครับ", "c.greet", "particle polite"),
    _e("ขอบคุณมากค่ะ", "c.small", "particle"),
    _e("ขอบคุณนะคะ", "c.small", "particle"),
    _e("ขอบคุณครับผม", "c.small", "particle"),
    _e("ขอบคุนครับ", "c.small", "typo"),
    _e("ขอบคุณค่ะ ไว้จะติดต่อมาใหม่", "c.small", "smalltalk_long"),
    _e("โอเคค่ะ", "c.small", "particle"),
    _e("โอเคครับ รับทราบ", "c.small", "particle"),
    _e("ok krub", "c.small", "karaoke"),
    _e("รับทราบค่ะ", "c.small", "particle"),
    _e("ได้ครับ", "c.small", "particle"),
    _e("ครับๆ", "c.small", "particle"),
    _e("บายค่ะ", "c.small", "goodbye"),
    _e("ลาก่อนครับ", "c.small", "goodbye"),
    _e("แค่นี้ก่อนนะคะ", "c.small", "goodbye"),
    _e("พอแล้วครับ ขอบคุณ", "c.small", "goodbye"),
    _e("🙏🙏", "c.small", "emoji"),
    _e("👍🏻", "c.small", "emoji_skin"),
    _e("55555 โอเค", "c.small", "laugh"),
    # ---- help -----------------------------------------------------------------
    _e("ใช้ยังไงคะเนี่ย", "c.help", "particle"),
    _e("ใช้งานยังไงอ่ะ", "c.help", "particle"),
    _e("ต้องทำยังไงบ้างครับ", "c.help", "particle"),
    _e("ไม่รู้จะเริ่มยังไงเลย", "c.help", "colloquial"),
    _e("งงมาก", "c.help", "colloquial"),
    _e("งงอ่ะ", "c.help", "particle"),
    _e("ช่วยบอกวิธีใช้หน่อย", "c.help", "polite_prefix"),
    _e("รบกวนสอนใช้หน่อยค่ะ", "c.help", "polite_prefix particle"),
    _e("มีอะไรให้ทำได้บ้าง", "c.help", "question"),
    _e("บอทนี้ช่วยอะไรได้บ้างคะ", "c.help", "question particle"),
    _e("how to use?", "c.help", "english"),
    _e("HELP", "c.help", "english_upper"),
    _e("Menu", "c.help", "english_case"),
    _e("เมนูหน่อย", "c.help", "particle"),
    _e("ขอเมนู", "c.help", "polite_prefix"),
    _e("จะแจ้งซ่อมต้องทำไง", "c.help", "buried question"),
    # ---- fault reports: plain, particles, typos, dialect ----------------------
    _e("แอร์ไม่เย็นครับ", "c.fault", "particle"),
    _e("แอร์ไม่เย็นเลยอ่ะ", "c.fault", "particle"),
    _e("แอร์ไม่เย็นค่า", "c.fault", "particle"),
    _e("แอร์มันไม่เย็นอะคับ", "c.fault", "particle typo"),
    _e("แอไม่เย็น", "c.fault", "typo_missing"),
    _e("แอร์ไม่เย้น", "c.fault", "typo_tone"),
    _e("แอร์ไม่เย็นนนน", "c.fault", "typo_dup"),
    _e("ตู้เย็นไม่เย็นน", "c.fault", "typo_dup"),
    _e("แอร์เสียครับ ช่วยด้วย", "c.fault", "multi_intent help_word"),
    _e("ซ่อมแอร์ครับ", "c.fault", "particle"),
    _e("ซ้อมแอร์", "c.fault", "typo_tone"),
    _e("ซอมแอร์หน่อย", "c.fault", "typo_missing particle"),
    _e("ขอช่างมาซ้อมแอร์ที", "c.fault", "typo_tone particle polite_prefix"),
    _e("อยากแจ้งซ้อม", "c.fault", "typo_tone"),
    _e("แจ้งซอม", "c.fault", "typo_missing"),
    _e("จ้งซ่อม", "c.fault", "typo_missing"),
    _e("แจ้งซ่อมคับ แอร์ไม่เย็น", "c.fault", "particle with_data"),
    _e("อยากแปงแอร์", "c.fault", "dialect_isan"),
    _e("แอร์เพ", "c.fault", "dialect_isan"),
    _e("แอร์บ่เย็น", "c.fault", "dialect_isan"),
    _e("แอร์บ่เย็นเด้อ", "c.fault", "dialect_isan particle"),
    _e("ตู้เย็นบ่เย็นจ้า", "c.fault", "dialect_isan particle"),
    _e("แอร์เสียแล้วเจ้า", "c.fault", "dialect_north particle"),
    _e("แอร์บ่เย็นเจ้า", "c.fault", "dialect_north particle"),
    _e("แอร์ไม่เย็นหม้าย", "c.fault", "dialect_south"),
    _e("แอร์เสียแล้วหนิ", "c.fault", "dialect_south particle"),
    _e("อยากหื้อช่างมาผ่อ", "c.fault", "dialect_north"),
    _e("air not cold", "c.fault", "english"),
    _e("AC not cooling", "c.fault", "english"),
    _e("Air con broken", "c.fault", "english"),
    _e("aircon mai yen", "c.fault", "karaoke"),
    _e("sang som air", "c.fault", "karaoke"),
    _e("จะ แจ้ง ซ่อม ค่ะ", "c.fault", "spaced"),
    _e("แอร์ mai yen", "c.fault", "mixed karaoke"),
    _e("แอร์ leak น้ำหยด", "c.fault", "mixed"),
    _e("compressor ดังมาก", "c.fault", "mixed"),
    _e("เครื่องซักผ้าไม่ปั่นหมาด", "c.fault", "symptom_only"),
    _e("น้ำไม่ไหล", "c.fault", "symptom_only"),
    _e("เปิดไม่ติด", "c.fault", "symptom_only"),
    _e("มีเสียงดังตอนเปิด", "c.fault", "symptom_only"),
    _e("ไฟกระพริบ", "c.fault", "symptom_only unlisted_marker"),
    _e("กลิ่นไหม้", "c.fault", "symptom_only unlisted_marker"),
    _e("เย็นบ้างไม่เย็นบ้าง", "c.fault", "symptom_only"),
    _e("น้ำแข็งเกาะ", "c.fault", "symptom_only unlisted_marker"),
    _e("รีโมทหาย", "c.fault", "symptom_only unlisted_marker"),
    _e("แอร์", "c.product_or_fault", "product_only"),
    _e("ตู้เย็น", "c.product_or_fault", "product_only"),
    _e("เครื่องซักผ้า Samsung", "c.product_or_fault", "product_only mixed"),
    _e("แอร์ Daikin 12000", "c.product_or_fault", "product_only mixed"),
    # urgency / complaint
    _e("ด่วนมาก แอร์เสีย ร้อนมาก", "c.fault", "urgency"),
    _e("ด่วน!!! ตู้เย็นดับ ของจะเสียหมด", "c.fault", "urgency punctuation"),
    _e("รีบมากค่ะ แอร์ห้องนอนไม่เย็น มีเด็กเล็ก", "c.fault", "urgency runon"),
    _e("ช่วยด่วนเลยครับ น้ำรั่วเต็มห้อง", "c.fault", "urgency polite_prefix"),
    _e("เร่งหน่อยนะคะ ร้อนจะตายแล้ว", "c.urgent_vague", "urgency vague"),
    _e("ด่วน", "c.urgent_vague", "urgency bare"),
    # runon / voice-to-text / buried
    _e("สวัสดีครับพอดีแอร์ที่ซื้อไปเมื่อเดือนก่อนมันไม่เย็นเลยอยากให้มาดูหน่อยครับอยู่บ้านช่วงบ่าย", "c.fault", "runon buried greeting"),
    _e("สวัสดีค่ะคือว่าตู้เย็นที่บ้านมันมีเสียงดังมากตอนกลางคืนไม่รู้เป็นอะไรอยากให้ช่างมาเช็คหน่อยค่ะ", "c.fault", "runon buried greeting"),
    _e("คือแบบว่าแอร์เปิดแล้วมันมีน้ำหยดลงมาเปียกพื้นหมดเลยอ่ะค่ะ", "c.fault", "runon particle"),
    _e("พอดีว่าเครื่องทำน้ำอุ่นน้ำไม่ร้อนเลยตั้งแต่เมื่อวานอาบน้ำเย็นมาสองวันแล้ว", "c.fault", "runon buried"),
    _e("อยากสอบถามว่าถ้าแอร์ไม่เย็นแล้วมีน้ำหยดต้องทำยังไงคะ", "c.fault_question", "buried question"),
    _e("เออ ตกลงแอร์ที่แจ้งไปมันยังไม่เย็นเลยนะ", "c.fault", "buried colloquial"),
    _e("ขอโทษนะคะ พอดีว่าเครื่องซักผ้าเปิดไม่ติดค่ะ", "c.fault", "buried polite_prefix"),
    _e("รบกวนด้วยค่ะ แอร์ไม่เย็น", "c.fault", "polite_prefix"),
    _e("รบกวนช่างมาดูแอร์ให้หน่อยได้ไหมคะ", "c.fault", "polite_prefix question"),
    _e("ขอนัดช่างมาล้างแอร์ได้มั้ยคะ", "c.fault", "question particle"),
    _e("ล้างแอร์ราคาเท่าไหร่ อยากล้าง 2 ตัว", "c.price", "price multi_intent"),
    _e("ช่างว่างมาดูวันเสาร์ไหมครับ", "c.fault_question", "question service"),
    _e("มีช่างมาติดตั้งแอร์ให้ไหม", "c.fault_question", "question service"),
    _e("ติดตั้งแอร์ใหม่ 1 เครื่อง บ้านอยู่บางนา", "c.fault", "with_data address"),
    _e("แอร์ไม่เย็น บ้านเลขที่ 99/1 ซ.สุขุมวิท 22 สะดวกพรุ่งนี้บ่าย", "c.fault", "with_data address date"),
    _e("แอร์ไม่เย็น โทร 0812345678", "c.fault", "with_data phone"),
    _e("แอร์ไม่เย็น SN12345678", "c.fault", "with_data serial"),
    _e("SN12345678 แอร์ไม่เย็น", "c.fault", "with_data serial_first"),
    _e("แอร์ไม่เย็นครับ แล้วก็ขอดูสถานะงานเก่าด้วย", "c.fault", "multi_intent"),
    _e("แจ้งซ่อมแอร์ และขอเลื่อนงานเดิมด้วย", "c.fault", "multi_intent"),
    # ---- job status ----------------------------------------------------------
    _e("ช่างจะมากี่โมงคะ", "c.status", "question particle"),
    _e("ช่างมาถึงไหนแล้ว", "c.status", "question"),
    _e("ช่างมารึยัง", "c.status", "question typo"),
    _e("ช่างมาหรือยังคะ", "c.status", "question particle"),
    _e("ช่างจะมาวันไหน", "c.status", "question"),
    _e("งานที่แจ้งไปเมื่อวานเป็นไงบ้าง", "c.status", "question colloquial"),
    _e("ที่แจ้งไปได้เรื่องยัง", "c.status", "question colloquial"),
    _e("เมื่อไหร่จะซ่อมเสร็จ", "c.status", "question"),
    _e("ซ่อมเสร็จรึยังครับ", "c.status", "question particle"),
    _e("สถานะค่ะ", "c.status", "particle"),
    _e("สถานะงานหน่อย", "c.status", "particle"),
    _e("ขอดูสถานะหน่อยครับ", "c.status", "polite_prefix particle"),
    _e("เช็คสถานะงานหน่อยค่ะ", "c.status", "particle"),
    _e("เช็กสถานะ", "c.status", "typo"),
    _e("เชคสถานะ", "c.status", "typo"),
    _e("status krub", "c.status", "karaoke"),
    _e("STATUS", "c.status", "english_upper"),
    _e("งานผมถึงไหนแล้วครับ", "c.status", "question particle"),
    _e("งานของฉันค่ะ", "c.status", "particle"),
    _e("งานของผมครับ", "c.status", "particle"),
    _e("ดูงานที่แจ้งไว้", "c.status", "colloquial"),
    _e("งานที่แจ้งไว้", "c.status", "colloquial"),
    _e("รายการที่แจ้งซ่อม", "c.status", "colloquial"),
    _e("ประวัติการแจ้งซ่อม", "c.status", "colloquial"),
    _e("ช่างชื่ออะไร", "c.status", "question"),
    _e("ช่างเบอร์อะไรคะ", "c.status", "question particle"),
    _e("T-2026-0001 ถึงไหนแล้ว", "c.status", "with_data question"),
    _e("งาน T-2026-0001", "c.status", "with_data"),
    _e("ขอเลขงานหน่อย", "c.status", "polite_prefix particle"),
    # ---- warranty ------------------------------------------------------------
    _e("ประกันหมดยัง", "c.warranty", "question"),
    _e("ยังอยู่ในประกันไหมคะ", "c.warranty", "question particle"),
    _e("เครื่องผมประกันถึงเมื่อไหร่", "c.warranty", "question"),
    _e("ประกันของฉันค่ะ", "c.warranty", "particle"),
    _e("ขอดูประกันหน่อย", "c.warranty", "polite_prefix particle"),
    _e("เช็คประกันหน่อยครับ", "c.warranty", "particle"),
    _e("เช็คประกัน SN12345678", "c.warranty", "with_data"),
    _e("ประกัน", "c.warranty", "bare"),
    _e("warranty", "c.warranty", "english"),
    _e("ใบรับประกัน", "c.warranty", "bare"),
    _e("ซ่อมฟรีไหม ยังมีประกันอยู่", "c.warranty", "question multi_intent"),
    _e("ถ้าหมดประกันแล้วซ่อมคิดเท่าไหร่", "c.price", "question price warranty"),
    # ---- register ------------------------------------------------------------
    _e("ลงทะเบียนสินค้าค่ะ", "c.register", "particle"),
    _e("ลงทะเบียนหน่อย", "c.register", "particle"),
    _e("ขอลงทะเบียนเครื่อง", "c.register", "polite_prefix"),
    _e("ลงทะเบียน SN12345678", "c.register", "with_data"),
    _e("ลงทะเบียนสินค้า SN12345678 ครับ", "c.register", "with_data particle"),
    _e("register SN12345678", "c.register", "english with_data"),
    _e("SN12345678", "c.register", "bare_serial"),
    _e("sn12345678", "c.register", "bare_serial lower"),
    _e("S/N 12345678", "c.register", "serial_format"),
    _e("ซีเรียล SN12345678", "c.register", "with_data"),
    _e("ลงทะเบียนยังไง", "c.help_register", "question"),
    _e("เครื่องใหม่ อยากลงทะเบียนรับประกัน", "c.register", "buried"),
    # ---- contact / hours / location ------------------------------------------
    _e("ติดต่อร้านค่ะ", "c.contact", "particle"),
    _e("ขอเบอร์ร้านหน่อย", "c.contact", "polite_prefix particle"),
    _e("เบอร์ร้านอะไรคะ", "c.contact", "question particle"),
    _e("โทรหาร้านได้ที่ไหน", "c.contact", "question"),
    _e("ร้านเปิดกี่โมง", "c.contact", "question hours"),
    _e("ร้านเปิดวันอาทิตย์ไหม", "c.contact", "question hours"),
    _e("ร้านอยู่ที่ไหนคะ", "c.contact", "question location particle"),
    _e("ร้านอยู่แถวไหน", "c.contact", "question location"),
    _e("ขอที่อยู่ร้าน", "c.contact", "polite_prefix location"),
    _e("ไปที่ร้านได้ไหม", "c.contact", "question location"),
    _e("ร้านปิดกี่โมงครับ", "c.contact", "question hours particle"),
    _e("contact", "c.contact", "english"),
    _e("shop phone number?", "c.contact", "english question"),
    _e("ขอไลน์ร้าน", "c.contact", "polite_prefix"),
    # ---- reschedule / cancel -------------------------------------------------
    _e("ขอเลื่อนนัดหน่อยค่ะ", "c.resched", "polite_prefix particle"),
    _e("เลื่อนเป็นวันศุกร์ได้ไหม", "c.resched", "question"),
    _e("พรุ่งนี้ไม่สะดวกค่ะ ขอเป็นวันเสาร์", "c.resched", "buried"),
    _e("ช่างมาพรุ่งนี้ไม่ได้นะ ไม่อยู่บ้าน", "c.resched", "buried negation"),
    _e("ขอเปลี่ยนเวลาเป็นบ่ายสองได้มั้ย", "c.resched", "question particle"),
    _e("เลื่อนไปอาทิตย์หน้า", "c.resched", "colloquial"),
    _e("ขอเลื่อนเป็นวันที่ 15 ก.ย. 10 โมง", "c.resched", "with_data date"),
    _e("เลื่อนนัด T-2026-0001 วันศุกร์", "c.resched", "with_data"),
    _e("reschedule to friday", "c.resched", "english"),
    _e("ขอเลื่อนเป็นมะรืนแทน", "c.resched", "colloquial"),
    _e("ยกเลิกค่ะ", "c.cancel", "particle"),
    _e("ไม่ซ่อมแล้วครับ", "c.cancel", "particle"),
    _e("ขอยกเลิกนัดหน่อย", "c.cancel", "polite_prefix particle"),
    _e("ยกเลิกงานเมื่อกี้", "c.cancel", "correction"),
    _e("ไม่เอาแล้วค่ะ ซ่อมเองได้แล้ว", "c.cancel", "buried"),
    _e("ยกเลิกอันเมื่อกี้", "c.cancel", "correction"),
    _e("cancel job", "c.cancel", "english"),
    _e("ไม่ใช่งานนี้ งาน T-2026-0001", "c.correction", "negation correction"),
    _e("ไม่ใช่ๆ ผมหมายถึงแอร์ห้องนอน", "c.correction", "negation correction"),
    _e("แก้ที่อยู่เป็น 12/3 ถ.ลาดพร้าว", "c.profile_edit", "with_data address",
       ai={"action": "update", "entity": "profile", "fields": {"address": "12/3 ถ.ลาดพร้าว"}, "missing": []}),
    _e("เปลี่ยนเบอร์เป็น 0891112222", "c.profile_edit", "with_data phone correction",
       ai={"action": "update", "entity": "profile", "fields": {"phone": "0891112222"}, "missing": []}),
    _e("เบอร์ใหม่ 089-111-2222 นะคะ", "c.profile_edit", "with_data phone buried particle",
       ai={"action": "update", "entity": "profile", "fields": {"phone": "089-111-2222"}, "missing": []}),
    # ---- talk to a human / complaints ----------------------------------------
    _e("ขอคุยกับคนจริงๆ", "c.chat", "human"),
    _e("ขอคุยกับพนักงานหน่อยค่ะ", "c.chat", "human particle"),
    _e("ไม่อยากคุยกับบอท", "c.chat", "human negation"),
    _e("มีคนตอบไหม", "c.chat", "human question"),
    _e("ขอเจ้าหน้าที่ค่ะ", "c.chat", "human polite_prefix"),
    _e("แอดมินอยู่ไหม", "c.chat", "human question"),
    _e("คุยกับร้านหน่อย", "c.chat", "particle"),
    _e("talk to human", "c.chat", "english human"),
    _e("คุยกับร้าน ล้างแอร์ราคาเท่าไหร่", "c.chat", "with_data"),
    _e("ช่างมาช้ามาก รอมาสามชั่วโมงแล้ว", "c.complaint", "complaint"),
    _e("ซ่อมไปแล้วก็ยังเสียเหมือนเดิม ไม่พอใจมาก", "c.complaint_fault", "complaint"),
    _e("บริการแย่มาก", "c.complaint", "complaint"),
    _e("ช่างพูดจาไม่ดีเลย", "c.complaint", "complaint"),
    _e("อยากร้องเรียน", "c.complaint", "complaint"),
    _e("ทำไมช่างยังไม่มาอีก โทรก็ไม่รับ", "c.status", "complaint question"),
    # ---- price / products ----------------------------------------------------
    _e("ล้างแอร์เท่าไหร่คะ", "c.price", "price question particle"),
    _e("ราคาล้างแอร์", "c.price", "price"),
    _e("ค่าซ่อมประมาณเท่าไหร่", "c.price", "price question"),
    _e("ค่าแรงเท่าไหร่ครับ", "c.price", "price question particle"),
    _e("มีค่าตรวจเช็คไหม", "c.price", "price question"),
    _e("แอร์รุ่นไหนดี", "c.price", "product question"),
    _e("มีแอร์ 18000 btu ไหม", "c.price", "product question mixed"),
    _e("ขอราคาแอร์ daikin หน่อย", "c.price", "product polite_prefix mixed"),
    _e("อยากซื้อแอร์ใหม่", "c.price", "product"),
    _e("สินค้าค่ะ", "c.product_list", "particle"),
    _e("ดูสินค้าหน่อย", "c.product_list", "particle"),
    _e("มีสินค้าอะไรบ้าง", "c.product_list", "question"),
    _e("ค้นหา แอร์", "c.search", "search"),
    _e("หาแอร์ 12000", "c.search", "search"),
    _e("โปรโมชั่นมีไหม", "c.price", "question"),
    _e("ผ่อนได้ไหม", "c.price", "question payment"),
    _e("จ่ายเงินยังไง", "c.payment", "question payment"),
    _e("โอนเงินได้ไหม รับบัตรเครดิตไหม", "c.payment", "question payment"),
    _e("ขอใบเสร็จด้วยค่ะ", "c.payment", "polite_prefix particle"),
    # ---- profile / orders / language ----------------------------------------
    _e("ข้อมูลของฉันค่ะ", "c.profile", "particle"),
    _e("โปรไฟล์หน่อย", "c.profile", "particle"),
    _e("ดูข้อมูลตัวเอง", "c.profile", "colloquial"),
    _e("ผมชื่ออะไรในระบบ", "c.profile", "question"),
    _e("เป็นลูกค้าร้านไหนอยู่", "c.profile", "question"),
    _e("ประวัติการซื้อค่ะ", "c.orders", "particle"),
    _e("เคยซื้ออะไรไปบ้าง", "c.orders", "question"),
    _e("ขอดูประวัติ", "c.orders", "polite_prefix"),
    _e("เปลี่ยนภาษาค่ะ", "c.lang", "particle"),
    _e("ขอเป็นภาษาอังกฤษ", "c.lang", "polite_prefix"),
    _e("English", "c.lang", "english_case"),
    _e("eng", "c.lang", "english_abbrev"),
    _e("พูดไทยได้ไหม", "c.lang", "question"),
    _e("ภาษาไทยค่ะ", "c.lang", "particle"),
    # ---- in-progress report continuation ------------------------------------
    _e("99/1 ซอยสุขุมวิท 22 แขวงคลองเตย", "c.address_answer", "address", pre=["แอร์ไม่เย็น"]),
    _e("บ้านอยู่หมู่บ้านสวนสน ซอย 3 บ้านเลขที่ 45", "c.address_answer", "address runon", pre=["แอร์ไม่เย็น"]),
    _e("ที่อยู่เดิมครับ", "c.address_same", "colloquial", pre=["แอร์ไม่เย็น"]),
    _e("ที่เดิม", "c.address_same", "colloquial short", pre=["แอร์ไม่เย็น"]),
    _e("พรุ่งนี้บ่ายสอง", "c.date_answer", "date", pre=["แอร์ไม่เย็น", "99/1 ซอยสุขุมวิท 22"]),
    _e("วันเสาร์เช้าๆ", "c.date_answer", "date colloquial", pre=["แอร์ไม่เย็น", "99/1 ซอยสุขุมวิท 22"]),
    _e("ได้ทุกวันเลยค่ะ", "c.date_any", "date colloquial", pre=["แอร์ไม่เย็น", "99/1 ซอยสุขุมวิท 22"]),
    _e("เมื่อไหร่ก็ได้", "c.date_any", "date colloquial", pre=["แอร์ไม่เย็น", "99/1 ซอยสุขุมวิท 22"]),
    _e("วันจันทร์หน้าตอนสายๆ", "c.date_answer", "date colloquial", pre=["แอร์ไม่เย็น", "99/1 ซอยสุขุมวิท 22"]),
    _e("15/9 10.30", "c.date_answer", "date numeric", pre=["แอร์ไม่เย็น", "99/1 ซอยสุขุมวิท 22"]),
    _e("ช่างจะมากี่โมง", "c.status", "question mid_report", pre=["แอร์ไม่เย็น"]),
]

SALES = [
    # ---- greetings / small talk / help --------------------------------------
    _e("สวัสดีคับ", "s.greet", "particle typo"),
    _e("หวัดดีจ้า", "s.greet", "particle"),
    _e("ดีครับพี่", "s.greet", "particle"),
    _e("ขอบคุณค่ะ", "s.small", "particle"),
    _e("ขอบคุณมากครับผม", "s.small", "particle"),
    _e("โอเคจ้า", "s.small", "particle"),
    _e("รับทราบครับ", "s.small", "particle"),
    _e("เยี่ยมเลย", "s.small", "particle"),
    _e("ใช้ยังไงวะ", "s.help", "particle_rude"),
    _e("ใช้ไงอ่ะ", "s.help", "particle"),
    _e("สอนหน่อยดิ", "s.help", "particle"),
    _e("รบกวนแนะนำการใช้งานหน่อยครับ", "s.help", "polite_prefix particle"),
    _e("มีคำสั่งไรบ้าง", "s.help", "colloquial"),
    _e("พิมพ์อะไรได้บ้างครับ", "s.help", "question particle"),
    _e("help กูหน่อย", "s.help", "mixed rude"),
    _e("how do I add a customer", "s.help", "english question"),
    _e("เพิ่มลูกค้ายังไง", "s.help_or_create", "question"),
    _e("สร้างดีลยังไงครับ", "s.help_or_create", "question particle"),
    _e("ทำใบเสนอราคายังไง", "s.help_or_create", "question"),
    _e("สิทธิ์ของผมมีอะไรบ้าง", "s.capability", "question"),
    _e("ผมทำอะไรได้บ้างครับ", "s.help", "question particle"),
    _e("ทำอะไรกับดีลได้บ้าง", "s.capability", "question"),
    _e("ทำไรกับลูกค้าได้บ้าง", "s.capability", "question colloquial"),
    # ---- customers: list / search / detail ---------------------------------
    _e("ลูกค้าครับ", "s.customer_list", "particle"),
    _e("ขอดูลูกค้าหน่อยครับ", "s.customer_list", "polite_prefix particle"),
    _e("ขอรายชื่อลูกค้าทั้งหมดหน่อย", "s.customer_list", "polite_prefix particle"),
    _e("รายชื่อลูกค้าค่ะ", "s.customer_list", "particle"),
    _e("ลูกค้าทั้งหมดมีใครบ้างครับ", "s.customer_list", "question particle"),
    _e("มีลูกค้ากี่คนแล้ว", "s.customer_list", "question"),
    _e("ลิสต์ลูกค้า", "s.customer_list", "mixed"),
    _e("list ลูกค้า", "s.customer_list", "mixed"),
    _e("Customers", "s.customer_list", "english_case"),
    _e("ลูกค้าาา", "s.customer_list", "typo_dup"),
    _e("ลุกค้า", "s.customer_list", "typo"),
    _e("ขอดู lead ทั้งหมด", "s.customer_list", "mixed polite_prefix"),
    _e("lead มีใครบ้าง", "s.customer_list", "mixed question"),
    _e("ค้นหาลูกค้า สมชาย", "s.customer_search", "search"),
    _e("หาลูกค้าสมชายหน่อย", "s.customer_search", "search particle"),
    _e("หาสมชาย", "s.customer_search", "search short"),
    _e("สมชาย", "s.customer_search", "name_only"),
    _e("ลูกค้าชื่อสมชายครับ", "s.customer_search", "particle"),
    _e("ขอเบอร์สมชายหน่อย", "s.customer_search", "polite_prefix particle"),
    _e("สมชายเบอร์ไรนะ", "s.customer_search", "question colloquial"),
    _e("เบอร์คุณสมชายอะไรครับ", "s.customer_search", "question particle honorific"),
    _e("ค้นหา สม", "s.customer_search", "partial_name"),
    _e("ลูกค้าที่ชื่อขึ้นต้นด้วย สม", "s.customer_search", "partial_name"),
    _e("ค้นหาลูกค้าเบอร์ 0812345678", "s.customer_search", "search phone"),
    _e("0812345678", "s.customer_search", "phone_only"),
    _e("ใครเบอร์ 0812345678", "s.customer_search", "question phone"),
    _e("find customer somchai", "s.customer_search", "english"),
    _e("ข้อมูลลูกค้า C-2026-0001 ครับ", "s.customer_detail", "with_data particle"),
    _e("C-2026-0001", "s.customer_detail", "code_only"),
    _e("c-2026-0001", "s.customer_detail", "code_only lower"),
    _e("ขอดูข้อมูลของสมชายหน่อย", "s.customer_search", "polite_prefix particle"),
    _e("ลูกค้าคนนี้ใครดูแล", "s.customer_context", "question context"),
    # ---- customers: create / update / delete (AI expected) ------------------
    _e("เพิ่มลูกค้า สมหญิง ดีใจ 0898765432", "s.customer_create", "ai with_data",
       ai={"action": "create", "entity": "customer", "fields": {"first_name": "สมหญิง", "last_name": "ดีใจ", "phone": "0898765432"}, "missing": []}),
    _e("ลูกค้าใหม่ครับ สมหญิง ดีใจ เบอร์ 089-876-5432 สนใจแอร์ 2 ตัว", "s.customer_create", "ai with_data runon particle",
       ai={"action": "create", "entity": "customer", "fields": {"first_name": "สมหญิง", "last_name": "ดีใจ", "phone": "089-876-5432", "notes": "สนใจแอร์ 2 ตัว"}, "missing": []}),
    _e("0898765432 สมหญิง ดีใจ", "s.customer_create", "ai with_data order_phone_first"),
    _e("ลูกค้าโทรมา ชื่อสมหญิง อยากได้แอร์", "s.customer_create", "ai buried"),
    _e("เมื่อกี้มีคนโทรมาถามเรื่องแอร์ ชื่อพี่หญิง เบอร์ 0898765432", "s.customer_create", "ai runon buried"),
    _e("add customer Somying Deejai 0898765432", "s.customer_create", "ai english"),
    _e("เพิ่มลูกค้าครับ", "s.customer_create_bare", "particle"),
    _e("เพิ่ม lead", "s.customer_create_bare", "mixed"),
    _e("สร้างลูกค้าใหม่หน่อย", "s.customer_create_bare", "particle"),
    _e("เพิ่มลูกค้า สมหญิง", "s.customer_create", "ai partial_data"),
    _e("แก้เบอร์สมชายเป็น 0899999999", "s.customer_update", "ai with_data",
       ai={"action": "update", "entity": "customer", "fields": {"target_name": "สมชาย", "phone": "0899999999"}, "missing": []}),
    _e("สมชายเปลี่ยนเบอร์แล้วนะ เป็น 0899999999", "s.customer_update", "ai buried"),
    _e("เปลี่ยนเบอร์เป็น 0899999999", "s.customer_update", "ai correction no_target"),
    _e("ไม่ใช่ 0812 นะ เป็น 0899999999", "s.customer_update", "ai negation correction"),
    _e("ลบลูกค้าสมชายหน่อย", "s.lead_archive", "particle"),
    _e("ลบ lead สมชาย ออก", "s.lead_archive", "mixed"),
    _e("เอาสมชายออกจากรายชื่อ", "s.lead_archive", "colloquial"),
    _e("delete lead somchai", "s.lead_archive", "english"),
    _e("ลบลูกค้า", "s.lead_archive", "bare"),
    # ---- deals ----------------------------------------------------------------
    _e("ดีลครับ", "s.deal_list", "particle"),
    _e("ขอดูดีลหน่อย", "s.deal_list", "polite_prefix particle"),
    _e("ดีลทั้งหมดมีอะไรบ้าง", "s.deal_list", "question"),
    _e("Deals", "s.deal_list", "english_case"),
    _e("ดีลล", "s.deal_list", "typo_dup"),
    _e("ดิล", "s.deal_list", "typo"),
    _e("pipeline", "s.deal_list", "english jargon"),
    _e("ขอดู pipeline หน่อย", "s.deal_list", "mixed polite_prefix"),
    _e("ไปป์ไลน์", "s.deal_list", "transliteration"),
    _e("ดีลที่ยังไม่ปิดครับ", "s.deal_open", "particle"),
    _e("ดีลค้างมีไหม", "s.deal_open", "question"),
    _e("ดีลไหนยังเปิดอยู่บ้าง", "s.deal_open", "question"),
    _e("มีดีลค้างกี่ดีล", "s.deal_open", "question"),
    _e("ดีลของสมชายครับ", "s.deal_for_customer", "particle"),
    _e("สมชายมีดีลอะไรบ้าง", "s.deal_for_customer", "question"),
    _e("ขอดูดีลของสมชายหน่อย", "s.deal_for_customer", "polite_prefix particle"),
    _e("ข้อมูลดีล D-2026-0001 ครับ", "s.deal_detail", "particle with_data"),
    _e("D-2026-0001", "s.deal_detail", "code_only"),
    _e("ดีล D-2026-0001 เป็นไงบ้าง", "s.deal_detail", "question"),
    _e("d-2026-0001 ครับ", "s.deal_detail", "code lower particle"),
    _e("เปิดดีลให้สมชายหน่อย", "s.deal_create", "particle"),
    _e("สร้างดีลให้สมชายครับ มูลค่า 50000", "s.deal_create", "with_data amount particle"),
    _e("สร้างดีลใหม่ให้ สมชาย 50,000 บาท ปิดสิ้นเดือน", "s.deal_create", "with_data amount date"),
    _e("ดีลใหม่ สมชาย แอร์ 2 ตัว", "s.deal_create_ai", "ai with_data order"),
    _e("สมชายสนใจซื้อแอร์ 2 ตัว 30000", "s.deal_create_ai", "ai buried"),
    _e("เปิดดีล", "s.deal_create_bare", "bare"),
    _e("สร้างดีล", "s.deal_create_bare", "bare"),
    _e("create deal for somchai", "s.deal_create", "english"),
    _e("ปิดสำเร็จ D-2026-0001 ครับ", "s.deal_stage", "particle with_data"),
    _e("D-2026-0001 ปิดได้แล้ว", "s.deal_stage", "with_data order"),
    _e("ดีล D-2026-0001 ลูกค้าตกลงแล้วนะ", "s.deal_stage", "with_data buried particle"),
    _e("D-2026-0001 ลูกค้าไม่เอา", "s.deal_stage", "with_data lost"),
    _e("ดีล D-2026-0001 แพ้ ลูกค้าไปซื้อที่อื่น", "s.deal_stage", "with_data lost reason"),
    _e("won D-2026-0001", "s.deal_stage", "english"),
    _e("ปิดดีล D-2026-0001", "s.deal_stage", "ambiguous"),
    _e("ยอดขายครับ", "s.sales_summary", "particle"),
    _e("เดือนนี้ขายได้เท่าไหร่", "s.sales_summary", "question"),
    _e("ยอดเดือนนี้เท่าไหร่ครับ", "s.sales_summary", "question particle"),
    _e("สรุปยอดหน่อย", "s.sales_summary", "particle"),
    _e("ขายได้กี่บาทแล้ว", "s.sales_summary", "question colloquial"),
    _e("ยอดขายวันนี้", "s.sales_summary", "period"),
    _e("ดีลเกิน 10000 ครับ", "s.deal_value", "particle"),
    _e("ดีลที่มากกว่า 20,000", "s.deal_value", "with_data"),
    _e("ดีลมูลค่า 50000", "s.deal_by_amount", "with_data amount"),
    _e("ดีลไหนที่ 50000", "s.deal_by_amount", "question amount"),
    _e("ดีลใหญ่ๆ มีไหม", "s.deal_query", "question"),
    _e("ดีลใหญ่สุดคืออันไหน", "s.deal_query", "question"),
    _e("ดีลเดือนนี้มีอะไรบ้าง", "s.deal_query", "question"),
    _e("ดีลที่เลยกำหนดแล้ว", "s.deal_query", "colloquial"),
    _e("มีดีลไหนเลยกำหนดบ้าง", "s.deal_query", "question"),
    _e("ดีลที่แพ้ไป", "s.deal_query", "colloquial"),
    _e("ดีลที่ปิดได้แล้ว", "s.deal_query", "colloquial"),
    # ---- quotes ---------------------------------------------------------------
    _e("ทำใบเสนอราคาให้สมชายหน่อย", "s.quote_create", "particle"),
    _e("ออกใบเสนอราคา D-2026-0001 ครับ", "s.quote_create", "particle with_data"),
    _e("ขอใบเสนอราคาดีล D-2026-0001", "s.quote_create", "polite_prefix with_data"),
    _e("สร้าง quote D-2026-0001", "s.quote_create", "mixed"),
    _e("quotation D-2026-0001", "s.quote_create", "english"),
    _e("ใบเสนอราคาค่ะ", "s.quote_list_or_create", "particle bare"),
    _e("ขอดูใบเสนอราคาหน่อย", "s.quote_list", "polite_prefix particle"),
    _e("ใบเสนอราคาทั้งหมดครับ", "s.quote_list", "particle"),
    _e("ใบเสนอราคาที่ยังไม่ตอบ", "s.quote_list", "colloquial"),
    _e("ลดราคา Q-2026-0001 500 บาท", "s.quote_discount", "with_data"),
    _e("ส่วนลด 10% ให้ Q-2026-0001", "s.quote_discount", "with_data order"),
    _e("ลูกค้าตกลงใบเสนอราคาแล้ว", "s.quote_accept", "colloquial"),
    _e("ลูกค้าโอเคใบเสนอราคา Q-2026-0001", "s.quote_accept", "colloquial with_data"),
    _e("ส่งใบเสนอราคาให้ลูกค้าหน่อย", "s.quote_send", "particle"),
    _e("ขอ pdf ใบเสนอราคา", "s.quote_send", "mixed polite_prefix"),
    # ---- notes / reminders / appointments ------------------------------------
    _e("บันทึกว่าสมชายขอเลื่อนนะ", "s.note_create", "particle"),
    _e("จดไว้หน่อยว่าลูกค้าขอส่วนลด", "s.note_create", "polite_prefix particle"),
    _e("โน้ต: ลูกค้าจะโทรกลับ", "s.note_create", "colon"),
    _e("note ลูกค้าจะโทรกลับ", "s.note_create", "mixed"),
    _e("ลูกค้าสนใจซื้อบ้านด้วย", "s.note_ai", "ai free_text"),
    _e("สมชายบอกว่ารอเงินเดือนออกก่อน", "s.note_ai", "ai buried"),
    _e("ดูบันทึกของสมชาย", "s.note_list", "colloquial"),
    _e("ประวัติสมชาย", "s.note_list", "colloquial"),
    _e("เตือนพรุ่งนี้ 10 โมงโทรหาสมชาย", "s.reminder_create", "with_data"),
    _e("เตือนผมพรุ่งนี้ด้วยนะ โทรหาสมชาย", "s.reminder_create", "particle order"),
    _e("พรุ่งนี้ 10 โมง โทรหาสมชาย", "s.reminder_create", "ai no_verb"),
    _e("นัดสมชายวันศุกร์บ่ายสอง", "s.reminder_create", "with_data"),
    _e("นัดสมชาย ศุกร์นี้ บ่าย 2", "s.reminder_create", "with_data colloquial"),
    _e("ตั้งนัดวันที่ 15 กันยา สมชาย", "s.reminder_create", "with_data"),
    _e("สมชายจะมาดูของวันเสาร์ 10 โมง", "s.reminder_create", "ai buried"),
    _e("ลูกค้าจะเข้ามาที่ร้านพรุ่งนี้ตอนบ่าย", "s.reminder_create", "ai buried no_name"),
    _e("อย่าลืมโทรหาสมชายพรุ่งนี้", "s.reminder_create", "colloquial"),
    _e("remind me tomorrow call somchai", "s.reminder_create", "english"),
    _e("เตือน D-2026-0001 ศุกร์หน้า", "s.reminder_create", "with_data"),
    _e("นัดหมายวันนี้ครับ", "s.reminder_list", "particle"),
    _e("วันนี้มีนัดใครบ้าง", "s.reminder_list", "question"),
    _e("พรุ่งนี้มีนัดไหม", "s.reminder_list", "question"),
    _e("ขอดูนัดหมายหน่อย", "s.reminder_list", "polite_prefix particle"),
    _e("อาทิตย์นี้มีนัดอะไรบ้าง", "s.reminder_list", "question"),
    _e("เลื่อนนัดสมชายไปวันจันทร์", "s.reminder_move", "with_data"),
    _e("เปลี่ยนเวลานัดเป็น 14.00", "s.reminder_move", "with_data"),
    _e("ยกเลิกนัดสมชาย", "s.reminder_cancel", "with_data"),
    _e("ไม่ต้องเตือนเรื่องสมชายแล้ว", "s.reminder_cancel", "negation"),
    _e("ยกเลิกอันเมื่อกี้", "s.reminder_cancel", "correction"),
    # ---- today's work -----------------------------------------------------------
    _e("งานวันนี้ครับ", "s.work_today", "particle"),
    _e("วันนี้ต้องทำอะไรบ้าง", "s.work_today", "question"),
    _e("วันนี้มีอะไรบ้าง", "s.work_today", "question"),
    _e("today", "s.work_today", "english"),
    _e("Today?", "s.work_today", "english question"),
    _e("มีอะไรต้องตามบ้าง", "s.work_upcoming", "question colloquial"),
    _e("งานค้างครับ", "s.work_upcoming", "particle"),
    _e("สัปดาห์นี้มีอะไรบ้าง", "s.work_upcoming", "question"),
    _e("อาทิตย์นี้ต้องทำอะไร", "s.work_upcoming", "question"),
    # ---- tickets on sales OA ---------------------------------------------------
    _e("งานซ่อมครับ", "s.ticket_list", "particle"),
    _e("งานซ่อมมีอะไรบ้าง", "s.ticket_list", "question"),
    _e("มีงานซ่อมค้างไหม", "s.ticket_list", "question"),
    _e("งานซ่อมวันนี้มีไหม", "s.ticket_list", "question"),
    _e("ticket", "s.ticket_list", "english"),
    _e("งานที่ยังไม่ได้มอบหมาย", "s.ticket_list", "colloquial"),
    _e("มอบหมาย T-2026-0001 ให้สมศักดิ์ครับ", "s.ticket_assign", "particle with_data"),
    _e("ให้สมศักดิ์ไป T-2026-0001", "s.ticket_assign", "order"),
    _e("T-2026-0001 ให้สมศักดิ์", "s.ticket_assign", "order short"),
    _e("จ่ายงาน T-2026-0001 ให้ทีมแอร์", "s.ticket_assign", "with_data"),
    _e("สมศักดิ์ไปงาน T-2026-0001 นะ", "s.ticket_assign", "order particle"),
    _e("assign T-2026-0001 to Somsak", "s.ticket_assign", "english"),
    _e("มอบหมายงานให้สมศักดิ์", "s.ticket_assign", "no_code"),
    _e("มอบหมาย T-2026-0001", "s.ticket_assign", "no_target"),
    _e("ข้อมูลงาน T-2026-0001 หน่อย", "s.ticket_detail", "particle"),
    _e("T-2026-0001", "s.ticket_detail", "code_only"),
    _e("t-2026-0001", "s.ticket_detail", "code_only lower"),
    _e("งาน T-2026-0001 ถึงไหนแล้ว", "s.ticket_detail", "question"),
    _e("ใครรับงาน T-2026-0001", "s.ticket_detail", "question"),
    _e("ลูกค้าโทรมาแจ้งแอร์ไม่เย็น สมชาย 0812345678 บ้าน 99/1", "s.ticket_create", "ai with_data runon",
       ai={"action": "create", "entity": "ticket", "fields": {"target_name": "สมชาย", "issue_description": "แอร์ไม่เย็น", "service_address": "99/1"}, "missing": []}),
    _e("เปิดงานซ่อมให้สมชาย แอร์ไม่เย็น", "s.ticket_create", "ai"),
    _e("แจ้งซ่อม แอร์ไม่เย็น บ้านสมชาย", "s.ticket_create", "ai order"),
    _e("มีงานติดตั้งแอร์ที่บ้านคุณสมชายวันศุกร์", "s.ticket_create", "ai buried date"),
    _e("ใครว่างบ้างวันนี้", "s.technician_list", "question"),
    _e("ช่างว่างไหม", "s.technician_list", "question"),
    _e("รายชื่อช่างครับ", "s.technician_list", "particle"),
    _e("ช่างมีใครบ้างคะ", "s.technician_list", "question particle"),
    _e("ช่างค่ะ", "s.technician_list", "particle bare"),
    _e("technician", "s.technician_list", "english"),
    _e("รายการรออนุมัติครับ", "s.approval_list", "particle"),
    _e("มีอะไรรออนุมัติไหม", "s.approval_list", "question"),
    _e("มีรายงานรอตรวจมั้ย", "s.approval_list", "question particle"),
    _e("อะไรรอผมอยู่บ้าง", "s.approval_list", "question colloquial"),
    _e("pending", "s.approval_list", "english"),
    _e("approve", "s.approve", "english bare"),
    _e("อนุมัติ SR-2026-0001 ครับ", "s.approve", "particle with_data"),
    _e("อนุมัติเลย", "s.approve", "colloquial"),
    _e("ผ่านครับ", "s.approve", "colloquial particle"),
    _e("โอเคผ่าน SR-2026-0001", "s.approve", "colloquial with_data"),
    _e("ไม่อนุมัติ SR-2026-0001 รูปไม่ครบ", "s.reject", "with_data reason"),
    _e("ตีกลับ SR-2026-0001 ให้ช่างใส่อะไหล่ด้วย", "s.reject", "with_data reason"),
    _e("ไม่ผ่านครับ รูปไม่ชัด", "s.reject", "colloquial reason"),
    _e("SR-2026-0001 ไม่ผ่าน", "s.reject", "order"),
    # ---- shop / settings / team / warranty --------------------------------------
    _e("ข้อมูลร้านครับ", "s.shop_info", "particle"),
    _e("รหัสร้านเราคืออะไร", "s.shop_info", "question"),
    _e("ร้านเรารหัสอะไรครับ", "s.shop_info", "question particle"),
    _e("รหัสร้านหน่อย", "s.shop_info", "particle"),
    _e("ขอรหัสร้านให้ลูกค้าหน่อย", "s.shop_info", "polite_prefix particle"),
    _e("ขอรหัสเชิญช่างหน่อย", "s.invite", "polite_prefix particle"),
    _e("เพิ่มช่างใหม่ครับ", "s.invite", "particle"),
    _e("ช่างใหม่จะเข้าร้านยังไง", "s.invite", "question"),
    _e("เชิญช่าง", "s.invite", "bare"),
    _e("invite technician", "s.invite", "english"),
    _e("ข้อมูลบริษัทค่ะ", "s.company_view", "particle"),
    _e("เลขผู้เสียภาษีคือ 0105558012345", "s.company_update", "with_data"),
    _e("ที่อยู่บริษัท 99 ถ.สุขุมวิท กทม", "s.company_update", "with_data"),
    _e("ตั้งค่าร้าน", "s.settings", "bare"),
    _e("ตั้งค่า", "s.settings", "bare"),
    _e("ทีมช่างครับ", "s.team_list", "particle"),
    _e("มีทีมอะไรบ้าง", "s.team_list", "question"),
    _e("สร้างทีมช่าง แอร์", "s.team_create", "with_data"),
    _e("ตั้งทีมใหม่ชื่อ แอร์ มีสมศักดิ์", "s.team_create", "ai with_data"),
    _e("ลงทะเบียนสินค้า SN99999999 แอร์ ให้ สมชาย", "s.warranty_register", "with_data"),
    _e("ลงทะเบียน SN99999999 ให้สมชาย", "s.warranty_register", "with_data short"),
    _e("บันทึกเครื่องที่ขาย SN99999999 สมชาย", "s.warranty_register", "colloquial"),
    _e("รายการประกันครับ", "s.warranty_book", "particle"),
    _e("เครื่องที่ลงทะเบียนไว้ทั้งหมด", "s.warranty_book", "colloquial"),
    _e("เช็คประกัน SN12345678 หน่อย", "s.serial_enquiry", "particle"),
    _e("SN12345678 ประกันหมดยัง", "s.serial_enquiry", "question"),
    _e("เครื่อง SN12345678 ของใคร", "s.serial_enquiry", "question"),
    _e("สินค้าครับ", "s.product_list", "particle"),
    _e("ขอดูสินค้าหน่อย", "s.product_list", "polite_prefix particle"),
    _e("มีสินค้าอะไรบ้าง", "s.product_list", "question"),
    _e("เพิ่มสินค้า พัดลม FAN001 ราคา 1500", "s.product_create", "ai with_data"),
    _e("ข้อมูลของฉันครับ", "s.profile", "particle"),
    _e("โปรไฟล์ผม", "s.profile", "colloquial"),
    _e("เปลี่ยนภาษาครับ", "s.lang", "particle"),
    _e("english pls", "s.lang", "english"),
    _e("ขอเป็นอังกฤษ", "s.lang", "polite_prefix"),
    # ---- multi-intent / corrections / context ----------------------------------
    _e("ขอดูลูกค้าแล้วก็ดีลด้วย", "s.customer_list", "multi_intent"),
    _e("เพิ่มลูกค้าสมหญิง 0898765432 แล้วเปิดดีลให้เลย", "s.customer_create", "ai multi_intent"),
    _e("ไม่ใช่สมชาย สมหญิงต่างหาก", "s.correction", "negation correction"),
    _e("ไม่ใช่ดีลนั้น D-2026-0002", "s.correction", "negation correction"),
    _e("ยกเลิกอันเมื่อกี้", "s.undo", "correction"),
    _e("ผิด ขอแก้", "s.undo", "correction"),
    _e("อากาศวันนี้เป็นไง", "s.offtopic", "offtopic"),
    _e("เล่าเรื่องตลกหน่อย", "s.offtopic", "offtopic"),
    _e("ราคาแอร์เท่าไหร่", "s.product_price", "question"),
    _e("สรุปยอดขายเดือนที่แล้ว", "s.sales_summary", "period"),
    _e("ใครเป็นลูกค้าที่ซื้อเยอะสุด", "s.report_ai", "question"),
    _e("ช่วยเขียนข้อความหาลูกค้าหน่อย", "s.offtopic", "offtopic polite_prefix"),
    _e("จะปิดดีลได้กี่ดีลเดือนนี้", "s.deal_query", "question"),
    _e("ลูกค้าคนที่คุยเมื่อวานชื่ออะไรนะ", "s.customer_context", "question context"),
]

TECH = [
    # ---- greetings / small talk / help --------------------------------------
    _e("สวัสดีคับ", "t.greet", "particle typo"),
    _e("ดีครับพี่", "t.greet", "particle"),
    _e("ขอบคุณครับ", "t.small", "particle"),
    _e("ครับผม", "t.small", "particle"),
    _e("โอเคคับ", "t.small", "particle typo"),
    _e("รับทราบ", "t.small", "bare"),
    _e("ใช้ไงวะ", "t.help", "particle_rude"),
    _e("ใช้ยังไงครับพี่", "t.help", "particle"),
    _e("สอนหน่อยครับ", "t.help", "particle"),
    _e("ต้องกดอะไร", "t.help", "question colloquial"),
    _e("พิมพ์อะไรได้บ้าง", "t.help", "question"),
    _e("เมนูครับ", "t.help", "particle"),
    _e("ผมทำอะไรได้บ้าง", "t.help", "question"),
    _e("สิทธิ์ผมมีอะไรบ้าง", "t.capability", "question"),
    # ---- my jobs / open / team / all -----------------------------------------
    _e("งานครับ", "t.mine", "particle"),
    _e("งานผมครับ", "t.mine", "particle"),
    _e("งานของผมวันนี้", "t.mine", "colloquial"),
    _e("วันนี้มีงานอะไรบ้างครับ", "t.mine", "question particle"),
    _e("วันนี้ต้องไปไหนบ้าง", "t.mine", "question colloquial"),
    _e("มีงานไรบ้าง", "t.mine_or_open", "question colloquial"),
    _e("งานวันนี้มีมั้ย", "t.mine", "question particle"),
    _e("พรุ่งนี้มีงานไหม", "t.mine", "question"),
    _e("ตารางงานหน่อย", "t.mine", "particle"),
    _e("ขอดูตารางงานหน่อยครับ", "t.mine", "polite_prefix particle"),
    _e("คิวงานผม", "t.mine", "colloquial"),
    _e("งานผมมีไรบ้างวันนี้", "t.mine", "question colloquial"),
    _e("my jobs", "t.mine", "english"),
    _e("My Jobs", "t.mine", "english_case"),
    _e("jobs", "t.mine", "english bare"),
    _e("ngan wan nee", "t.mine", "karaoke"),
    _e("งาน วันนี้", "t.mine", "spaced"),
    _e("งานนน", "t.mine", "typo_dup"),
    _e("งานที่เปิดรับครับ", "t.open", "particle"),
    _e("มีงานว่างไหม", "t.open", "question"),
    _e("มีงานใหม่มั้ย", "t.open", "question particle"),
    _e("งานใหม่ๆ มีไหม", "t.open", "question"),
    _e("มีงานให้รับไหม", "t.open", "question"),
    _e("ขอดูงานที่ยังไม่มีคนรับ", "t.open", "polite_prefix"),
    _e("งานไหนยังว่างบ้าง", "t.open", "question"),
    _e("open jobs", "t.open", "english"),
    _e("งานของทีมครับ", "t.team", "particle"),
    _e("ทีมมีงานไหม", "t.team", "question"),
    _e("งานทีมแอร์", "t.team", "with_data"),
    _e("ทีมผมมีงานอะไรบ้าง", "t.team", "question"),
    _e("งานทั้งหมด", "t.all", "bare"),
    _e("รายการงานครับ", "t.all", "particle"),
    # ---- ticket detail / current job ------------------------------------------
    _e("ข้อมูลงาน T-2026-0001 ครับ", "t.detail", "particle with_data"),
    _e("T-2026-0001", "t.detail", "code_only"),
    _e("t-2026-0001", "t.detail", "code_only lower"),
    _e("T-2026-0001 ที่อยู่ไหน", "t.detail", "question with_data"),
    _e("งาน T-2026-0001 ลูกค้าเบอร์อะไร", "t.detail", "question with_data"),
    _e("งานนี้อยู่ไหนครับ", "t.current", "question particle"),
    _e("ลูกค้าเบอร์ไรครับ", "t.current", "question particle colloquial"),
    _e("บ้านลูกค้าอยู่ไหน", "t.current", "question"),
    _e("ที่อยู่ลูกค้าหน่อย", "t.current", "particle"),
    _e("ขอเบอร์ลูกค้าหน่อยครับ", "t.current", "polite_prefix particle"),
    _e("นัดกี่โมงนะ", "t.current", "question particle"),
    _e("ไปที่ไหนต่อ", "t.current", "question"),
    _e("งานถัดไปที่ไหน", "t.current", "question"),
    _e("ขอแผนที่หน่อย", "t.current", "polite_prefix"),
    _e("ลูกค้าชื่ออะไร", "t.current", "question"),
    # ---- claim / reject --------------------------------------------------------
    _e("รับงาน T-2026-0002 ครับ", "t.claim", "particle with_data"),
    _e("รับครับ", "t.claim", "particle"),
    _e("รับคับ", "t.claim", "particle typo"),
    _e("รับเลย", "t.claim", "particle"),
    _e("รับได้ครับ", "t.claim", "colloquial"),
    _e("ผมรับเองครับ", "t.claim", "particle"),
    _e("เดี๋ยวผมไปเอง", "t.claim", "ai colloquial"),
    _e("ขอรับงานนี้ครับ", "t.claim", "polite_prefix particle"),
    _e("งานนี้ผมเอา", "t.claim", "colloquial"),
    _e("เอางาน T-2026-0002", "t.claim", "colloquial with_data"),
    _e("ok รับงาน T-2026-0002", "t.claim", "mixed"),
    _e("รับ T-2026-0002", "t.claim", "short with_data"),
    _e("T-2026-0002 รับ", "t.claim", "order"),
    _e("accept", "t.claim", "english"),
    _e("rub ngan", "t.claim", "karaoke"),
    _e("รับงาน", "t.claim", "bare"),
    _e("รับงานครับ", "t.claim", "bare particle"),
    _e("ไม่รับครับ", "t.reject", "particle"),
    _e("ไม่ว่างครับ", "t.reject", "particle"),
    _e("ไปไม่ได้ครับ ป่วย", "t.reject", "particle reason"),
    _e("ไม่สะดวกครับ ติดงานอื่น", "t.reject", "particle reason"),
    _e("ปฏิเสธ T-2026-0001 ป่วย", "t.reject", "with_data reason"),
    _e("ปฏิเสธงาน T-2026-0001 ครับ ติดงานอื่น", "t.reject", "with_data reason particle"),
    _e("งาน T-2026-0001 ผมไปไม่ได้ครับ", "t.reject", "with_data buried"),
    _e("ไม่ไหวครับวันนี้", "t.reject", "colloquial"),
    _e("ขอไม่รับงานนี้นะครับ", "t.reject", "polite_prefix particle"),
    _e("บ่ว่าง", "t.reject", "dialect_isan"),
    _e("บ่ไปเด้อ", "t.reject", "dialect_isan"),
    _e("ไปบ่ได้", "t.reject", "dialect_isan"),
    _e("บ่ไหว", "t.reject", "dialect_isan"),
    _e("decline", "t.reject", "english"),
    _e("ไม่รับ", "t.reject", "bare"),
    # ---- check in ---------------------------------------------------------------
    _e("เช็คอินครับ", "t.checkin", "particle"),
    _e("เช็คอินแล้วนะ", "t.checkin", "particle"),
    _e("เช็กอิน", "t.checkin", "typo"),
    _e("เชคอิน", "t.checkin", "typo_missing"),
    _e("เช็คอินน", "t.checkin", "typo_dup"),
    _e("เช็ค อิน", "t.checkin", "spaced"),
    _e("check in", "t.checkin", "english"),
    _e("Check In", "t.checkin", "english_case"),
    _e("checkin", "t.checkin", "english"),
    _e("CHECKIN", "t.checkin", "english_upper"),
    _e("chek in", "t.checkin", "karaoke typo"),
    _e("chec in", "t.checkin", "karaoke typo"),
    _e("เช็คอิน T-2026-0001 ครับ", "t.checkin", "with_data particle"),
    _e("ถึงแล้วครับ", "t.checkin", "particle"),
    _e("ถึงละ", "t.checkin", "colloquial"),
    _e("ถึงแล้วว", "t.checkin", "typo_dup"),
    _e("ถึงบ้านลูกค้าแล้วครับ", "t.checkin", "particle"),
    _e("มาถึงหน้างานแล้ว", "t.checkin", "colloquial"),
    _e("ถึงหน้างานแล้วครับ เริ่มงานเลยนะ", "t.checkin", "multi_intent particle"),
    _e("ผมถึงแล้วนะครับ", "t.checkin", "particle"),
    _e("ถึงงาน T-2026-0001 แล้ว", "t.checkin", "with_data"),
    _e("อยู่หน้าบ้านลูกค้าแล้ว", "t.checkin", "colloquial"),
    _e("เริ่มงานได้", "t.checkin", "colloquial"),
    _e("เริ่มแล้ว", "t.checkin", "colloquial short"),
    _e("arrived", "t.checkin", "english"),
    _e("ถึงแล้ว เจอลูกค้าแล้ว", "t.checkin", "multi_intent"),
    _e("เช็คอินแล้วนะ แล้วก็ขอดูงานพรุ่งนี้ด้วย", "t.checkin", "multi_intent"),
    _e("ฮอดแล้ว", "t.checkin", "dialect_isan"),
    _e("มาฮอดแล้วเด้อ", "t.checkin", "dialect_isan particle"),
    _e("ถึงแล้วเจ้า", "t.checkin", "dialect_north particle"),
    _e("ถึงแล้วหนิ", "t.checkin", "dialect_south particle"),
    _e("teung laew krub", "t.checkin", "karaoke"),
    # on my way / late / not home / etc. (no deterministic handler today)
    _e("กำลังไปครับ", "t.on_my_way", "status"),
    _e("ออกเดินทางแล้ว", "t.on_my_way", "status"),
    _e("อีก 15 นาทีถึง", "t.on_my_way", "status with_data"),
    _e("รถติดครับ ไปช้าหน่อย", "t.late", "status"),
    _e("ไปสายนิดนึงนะครับ", "t.late", "status particle"),
    _e("ขอเลื่อนเป็นบ่ายสองนะครับ ติดงานเก่า", "t.reschedule", "status particle"),
    _e("ลูกค้าไม่อยู่บ้านครับ", "t.not_home", "status"),
    _e("ลูกค้าไม่อยู่ โทรไม่ติด", "t.not_home", "status"),
    _e("ไม่มีคนเปิดบ้าน", "t.not_home", "status colloquial"),
    _e("ลูกค้าขอเลื่อนเป็นพรุ่งนี้", "t.reschedule", "status"),
    _e("ต้องสั่งอะไหล่ครับ วันนี้ทำไม่จบ", "t.need_parts", "status"),
    _e("ขาดคอมเพรสเซอร์ ต้องเบิกของ", "t.need_parts", "status"),
    _e("วันนี้ทำไม่เสร็จ ต้องมาต่อพรุ่งนี้", "t.cannot_finish", "status"),
    _e("งานใหญ่กว่าที่คิด ขอมาต่ออีกวัน", "t.cannot_finish", "status"),
    _e("ส่งรูปให้แล้วนะครับ", "t.photo", "status"),
    _e("รูปหน้างานส่งไปแล้ว", "t.photo", "status"),
    _e("ถ่ายรูปแล้ว ดูรูปได้ยัง", "t.photo", "status question"),
    _e("ขอส่งรูป", "t.photo", "polite_prefix"),
    _e("ลูกค้าไม่ยอมเซ็น", "t.status_free", "status"),
    _e("ลูกค้าจ่ายเงินสดแล้ว 1500", "t.status_free", "status with_data"),
    # ---- check out / close -----------------------------------------------------
    _e("เสร็จแล้วครับ", "t.checkout", "particle", pre=["เช็คอิน T-2026-0001"]),
    _e("เสร็จละ", "t.checkout", "colloquial", pre=["เช็คอิน T-2026-0001"]),
    _e("เสร็จแล้วว", "t.checkout", "typo_dup", pre=["เช็คอิน T-2026-0001"]),
    _e("ปิดงานครับ", "t.checkout", "particle", pre=["เช็คอิน T-2026-0001"]),
    _e("ปิดงานหน่อย", "t.checkout", "particle", pre=["เช็คอิน T-2026-0001"]),
    _e("ปิดงาน T-2026-0001 ครับ", "t.checkout", "with_data particle", pre=["เช็คอิน T-2026-0001"]),
    _e("ซ่อมเสร็จแล้วครับ เปลี่ยนคอมเพรสเซอร์", "t.checkout", "with_data", pre=["เช็คอิน T-2026-0001"]),
    _e("งานเรียบร้อยครับ", "t.checkout", "colloquial", pre=["เช็คอิน T-2026-0001"]),
    _e("เรียบร้อย", "t.checkout", "colloquial short", pre=["เช็คอิน T-2026-0001"]),
    _e("จบงานแล้ว", "t.checkout", "colloquial", pre=["เช็คอิน T-2026-0001"]),
    _e("done", "t.checkout", "english", pre=["เช็คอิน T-2026-0001"]),
    _e("Done ครับ", "t.checkout", "mixed", pre=["เช็คอิน T-2026-0001"]),
    _e("finish", "t.checkout", "english variant", pre=["เช็คอิน T-2026-0001"]),
    _e("เช็คเอาท์", "t.checkout", "bare", pre=["เช็คอิน T-2026-0001"]),
    _e("เช็คเอ้าท์", "t.checkout", "typo", pre=["เช็คอิน T-2026-0001"]),
    _e("check out", "t.checkout", "english", pre=["เช็คอิน T-2026-0001"]),
    _e("checkout", "t.checkout", "english", pre=["เช็คอิน T-2026-0001"]),
    _e("แล้วเสร็จ", "t.checkout", "colloquial", pre=["เช็คอิน T-2026-0001"]),
    _e("เสร็จแล้วเด้อ", "t.checkout", "dialect_isan", pre=["เช็คอิน T-2026-0001"]),
    _e("แล้วเจ้า", "t.checkout", "dialect_north", pre=["เช็คอิน T-2026-0001"]),
    _e("เสร็จแล้วหนิ", "t.checkout", "dialect_south", pre=["เช็คอิน T-2026-0001"]),
    _e("set laew", "t.checkout", "karaoke", pre=["เช็คอิน T-2026-0001"]),
    _e("ปิดงาน T-2026-0001\nพบ: คอมรั่ว\nแก้: เปลี่ยนคอม\nอะไหล่: คอมเพรสเซอร์", "t.checkout", "with_data multiline", pre=["เช็คอิน T-2026-0001"]),
    _e("ปิดงาน พบคอมรั่ว เปลี่ยนคอมแล้ว", "t.checkout", "with_data oneline", pre=["เช็คอิน T-2026-0001"]),
    _e("เสร็จแล้ว ลูกค้าเซ็นแล้ว จ่ายเงินสด", "t.checkout", "with_data note", pre=["เช็คอิน T-2026-0001"]),
    _e("เสร็จแล้วครับ", "t.checkout_no_checkin", "particle no_checkin"),
    _e("ปิดงาน T-2026-0001", "t.checkout_no_checkin", "with_data no_checkin"),
    # report answers mid-flow
    _e("คอมเพรสเซอร์รั่ว", "t.report_answer", "answer", pre=["เช็คอิน T-2026-0001", "ปิดงาน"]),
    _e("เจอคอมรั่วครับ", "t.report_answer", "answer particle", pre=["เช็คอิน T-2026-0001", "ปิดงาน"]),
    _e("ไม่มีอะไร", "t.report_answer", "answer negation", pre=["เช็คอิน T-2026-0001", "ปิดงาน"]),
    _e("-", "t.report_answer", "answer dash", pre=["เช็คอิน T-2026-0001", "ปิดงาน"]),
    _e("ข้าม", "t.report_answer", "answer skip", pre=["เช็คอิน T-2026-0001", "ปิดงาน"]),
    _e("ยกเลิก", "t.report_cancel", "cancel mid_flow", pre=["เช็คอิน T-2026-0001", "ปิดงาน"]),
    _e("ไม่ใช่งานนี้ งาน T-2026-0002", "t.correction", "negation correction", pre=["เช็คอิน T-2026-0001", "ปิดงาน"]),
    # ---- reports / warranty / profile / language ----------------------------------
    _e("รายงานของผมครับ", "t.report_list", "particle"),
    _e("ดูรายงานหน่อย", "t.report_list", "particle"),
    _e("รายงานที่ส่งไป", "t.report_list", "colloquial"),
    _e("ส่งรายงาน", "t.checkout_or_report", "bare"),
    _e("ขอ pdf งาน T-2026-0001", "t.report_pdf", "mixed with_data"),
    _e("ออกรายงาน T-2026-0001", "t.report_pdf", "with_data"),
    _e("เช็คประกัน SN12345678 หน่อยครับ", "t.serial", "particle"),
    _e("SN12345678 ยังมีประกันไหม", "t.serial", "question"),
    _e("เครื่องนี้ประกันหมดยัง SN12345678", "t.serial", "question order"),
    _e("ประกันเครื่องนี้ยังอยู่ไหม", "t.serial_no_sn", "question no_serial"),
    _e("เช็คประกันหน่อย", "t.serial_no_sn", "no_serial"),
    _e("ข้อมูลของผมครับ", "t.profile", "particle"),
    _e("โปรไฟล์", "t.profile", "bare"),
    _e("แก้เบอร์เป็น 0899999999", "t.profile_edit", "ai with_data",
       ai={"action": "update", "entity": "profile", "fields": {"phone": "0899999999"}, "missing": []}),
    _e("เบอร์ผมเปลี่ยนเป็น 0899999999 นะครับ", "t.profile_edit", "ai buried particle",
       ai={"action": "update", "entity": "profile", "fields": {"phone": "0899999999"}, "missing": []}),
    _e("เปลี่ยนภาษาครับ", "t.lang", "particle"),
    _e("english", "t.lang", "english"),
    _e("ขอไทย", "t.lang", "polite_prefix short"),
    _e("เปลี่ยนร้าน", "t.switch_shop", "bare"),
    # crafted-AI probes: what happens downstream when the model does understand
    _e("ลูกค้าไม่อยู่บ้าน ขอเลื่อนไปพรุ่งนี้บ่าย", "t.ai_ticket_update", "ai crafted",
       ai={"action": "update", "entity": "ticket", "fields": {"scheduled_date": "พรุ่งนี้", "scheduled_time": "บ่าย"}, "missing": []}),
    _e("เปลี่ยนคอมเพรสเซอร์ให้แล้ว เจอท่อรั่วด้วย", "t.ai_report_create", "ai crafted",
       ai={"action": "create", "entity": "service_report", "fields": {"found_issue": "ท่อรั่ว", "work_done": "เปลี่ยนคอมเพรสเซอร์", "parts_changed": "คอมเพรสเซอร์"}, "missing": []}),
    _e("กำลังไปครับ อีก 15 นาที", "t.ai_status_update", "ai crafted",
       ai={"action": "update", "entity": "ticket", "fields": {"status": "on_the_way"}, "missing": []}),
]

ALL = [dict(e, oa="customer") for e in CUSTOMER] + [dict(e, oa="sales") for e in SALES] + [dict(e, oa="technician") for e in TECH]
